= Программное обеспечение для формирования усиленной подписи

{wc} поддерживает два типа подписи: простая и усиленная. Формирование простой подписи доступно без дополнительных настроек, но должно быть предусмотрено сценарием подписания.

include::user:partial$excerpts.adoc[tags=signature]
Необходимые компоненты перечислены далее.

[#requirements]
== Общие требования

В справочнике _Системные настройки_, в разделе menu:{bo}[Подписи и шифрование] должен быть выбран криптопровайдер и алгоритм подписи, соответствующие используемому сертификату ЭП. В частности, для работы с сертификатами КриптоПро должен быть выбран провайдер КриптоПро (_Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider_).

[NOTE]
====
Дополнительная информация по настройке подписания и шифрования приведена в документации по администрированию модуля {bo}, раздел "xref:dev@backoffice:admin:system-settings.adoc#signature-cypher[Подписи и шифрование]".
====

Далее перечислены требования для формирования и проверки усиленной и усовершенствованной подписи со стандартным (не облачным) сертификатом. См. также xref:5.5.5@backoffice::requirements.adoc#crypto-pro[требования для модуля "{bo}"].

****
// tag::expiredCryptoPro[]
Если лицензия на компоненты КриптоПро CSP истекла, добавление новых подписей блокируется. Если подпись была добавлена ранее и срок действия сертификата ЭП не истёк, возможность проверки такой подписи не будет заблокирована. Проверка старых подписей выполняется успешно в любом случае.
// end::expiredCryptoPro[]

По вопросам получения компонентов криптопровайдера КриптоПро следует обращаться в компанию ООО КРИПТО-ПРО.
****

[#bes]
== Формирование и проверка подписи

.Требования к серверу:
. КриптоПро CSP версии {csp-v}.
. xref:dev@engineer:ROOT:java-service.adoc[Криптосервис обслуживания ЭП] для проверки и формирования простой подписи и подписей CAdES-BES и CAdES-X Long Type 1.
. xref:user:prepare-add-components.adoc#cryptoPro[КриптоПро ЭЦП Browser plug-in] версии {sign-plugin}.
. {root-cert} Сертификат должен быть установлен в хранилище _Доверенные корневые центры сертификации_ на уровне _Локальный компьютер_.

.Требования к клиентским рабочим местам:
. Операционная система: Windows или Mac OS, Linux (версии см. в требованиях https://www.cryptopro.ru/products/csp/compare[КриптоПро CSP]).
. Веб-браузер: Google Chrome, Яндекс.Браузер или Microsoft Edge на Chromium (поддерживаемые версии см. в пункте xref:requirements-software.adoc#browser[Необходимое программное обеспечение]).
. xref:user:prepare-add-components.adoc#cryptoPro[КриптоПро ЭЦП Browser plug-in] версии {sign-plugin}.
. Квалифицированный сертификат пользователя. Должен быть установлен в хранилище _Личное_ на уровне _Текущий пользователь_.
// . КриптоПро TSPCOM версии {tspcom-v} -- компонент необходим для создания усиленной подписи Cades-X-Long-Type-1.

// tag::macOS[]
NOTE: Здесь указано название хранилищ в ОС Windows. Шаги, необходимые для настройки КриптоПро в ОС Mac OS и Astra Linux можно найти в https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/232/0/rbot-s-kriptopro-csp-v-macos[документации КриптоПро].
// end::macOS[]

// .Компоненты криптопровайдера КриптоПро:
// . КриптоПро TSPCOM версии {tspcom-v} -- компонент необходим для создания усиленной подписи Cades-X-Long-Type-1.

