= Программное обеспечение для формирования усиленной подписи

{wc} поддерживает два типа подписи: простая и усиленная. Формирование простой подписи доступно без дополнительных настроек, но должно быть предусмотрено сценарием подписания.

include::user:partial$excerpts.adoc[tags=signature]
Необходимые компоненты перечисленные далее.

[#requirements]
== Общие требования

В справочнике _Системные настройки_, в разделе menu:{bo}[Подписи и шифрование] должен быть выбран криптопровайдер и алгоритм подписи, соответствующие используемому сертификату ЭП. В частности, для работы с сертификатами КриптоПро должен быть выбран провайдер КриптоПро (_Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider_).

[NOTE]
====
Дополнительная информация по настройке подписания и шифрования приведена в _Руководстве администратора модуля {bo}_.
====

Набор необходимых компонентов для работы с подписью зависит от типа подписи. Далее перечислены требования для формирования и проверки усиленной и усовершенствованной подписи со стандартным (не облачным) сертификатом. См. также xref:5.5.5@backoffice::requirements.adoc#crypto-pro[требования для модуля "{bo}"].

****
// tag::expiredCryptoPro[]
Если лицензия на компоненты КриптоПро CSP истекла, добавление новых подписей блокируется. Если подпись была добавлена ранее и срок действия сертификата ЭП не истёк, возможность проверки такой подписи не будет заблокирована. Проверка старых подписей выполняется успешно в любом случае.
// end::expiredCryptoPro[]

По вопросам получения компонентов криптопровайдера КриптоПро следует обращаться в компанию ООО КРИПТО-ПРО.
****

[#bes]
== Формирование и проверка усиленной подписи (CAdES BES)

.Требования к серверу:
. Не требуются Компоненты КриптоПро CSP, КриптоПро TSP Client и КриптоПро OCSP Client и лицензия на них.

.Требования к клиентским рабочим местам:
. Операционная система: Windows или Mac OS.
. Веб-браузер: Google Chrome, Яндекс.Браузер или Microsoft Edge на Chromium (поддерживаемые версии см. в пункте xref:requirements-software.adoc[Необходимое программное обеспечение]).
. КриптоПро ЭЦП Browser plug-in версии {sign-plugin} (https://www.cryptopro.ru/products/cades/plugin[ссылка для загрузки]).
. CryptoPro Extension for CAdES Browser Plug-in версии {chrome-ext} (https://chrome.google.com/webstore/detail/cryptopro-extension-for-c/iifchhfnnmpdbibifmljnfjhpififfog[ссылка для загрузки]).
. Неквалифицированный сертификат пользователя. Сертификат должен быть установлен в хранилище _Личное_ на уровне _Текущий пользователь_.
. Приложение КриптоПро https://www.cryptopro.ru/products/mydss2#law[myDSS 2.0] или https://www.cryptopro.ru/products/dss/mobile/dssclient[DSS Client] для работы с подписью xref:user:docs-sign.adoc#mobile[на мобильных устройствах]. Приложения обладают схожей функциональностью, рекомендуется использовать DSS Client как официальное приложение КриптоПро.
. Компоненты КриптоПро TSP Client, КриптоПро OCSP Client, КриптоПро CSP и лицензия на них не требуются.

[#long]
== Формирование и проверка усовершенствованной подписи (CAdES-X Long Type 1)

.Требования к серверу:
// . https://www.cryptopro.ru/downloads[КриптоПро CADESCOM версия {cades}].
. Требуется установить Компоненты КриптоПро CSP {csp-v} с соответствующей лицензией.
. {root-cert} Сертификат должен быть установлен в хранилище _Доверенные корневые центры сертификации_ на уровне _Локальный компьютер_.
. Компоненты КриптоПро TSP Client и КриптоПро OCSP Client и лицензия на них не требуются.

.Требования к клиентским рабочим местам:
. Операционная система: Windows или Mac OS (версии см. в требованиях https://www.cryptopro.ru/products/csp/compare[КриптоПро CSP]).
. Веб-браузер: Google Chrome, Яндекс.Браузер или Microsoft Edge на Chromium (поддерживаемые версии см. в пункте xref:requirements-software.adoc#browser[Необходимое программное обеспечение]).
. xref:user:prepare-add-components.adoc#cryptoPro[КриптоПро ЭЦП Browser plug-in] версии {sign-plugin}.
. CryptoPro Extension for CAdES Browser Plug-in версии {chrome-ext} (https://chrome.google.com/webstore/detail/cryptopro-extension-for-c/iifchhfnnmpdbibifmljnfjhpififfog[ссылка для загрузки]).
. КриптоПро CSP версии {csp-v}, потребуется лицензия для каждого пользователя.
. Компоненты КриптоПро TSP Client и КриптоПро OCSP Client и лицензия на них для каждого пользователя.
. {root-cert} Должен быть установлен в хранилище _Доверенные корневые центры сертификации_ на уровне _Локальный компьютер_.
. Квалифицированный сертификат пользователя. Должен быть установлен в хранилище _Личное_ на уровне _Текущий пользователь_.
+
// tag::macOS[]
NOTE: Здесь указано название хранилищ в ОС Windows. Шаги, необходимые для настройки КриптоПро в ОС Mac OS, можно найти в https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/232/0/rbot-s-kriptopro-csp-v-macos[документации КриптоПро].
// end::macOS[]

// .Компоненты криптопровайдера КриптоПро:
// . КриптоПро TSPCOM версии {tspcom-v} -- компонент необходим для создания усиленной подписи Cades-X-Long-Type-1.

