= Программное обеспечение для формирования усиленной подписи

{wc} поддерживает два типа подписи: простая и усиленная. Формирование простой подписи доступно без дополнительных настроек, но должно быть предусмотрено сценарием подписания.

include::user:partial$excerpts.adoc[tags=signature]
Необходимые компоненты перечисленные далее.

[#requirements]
== Общие требования

В справочнике _Системные настройки_, в разделе menu:{bo}[Подписи и шифрование] должен быть выбран криптопровайдер и алгоритм подписи, соответствующие используемому сертификату ЭП. В частности, для работы с сертификатами КриптоПро должен быть выбран провайдер КриптоПро (_Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider_).

[NOTE]
====
Дополнительная информация по настройке подписания и шифрования приведена в документации по администрированию модуля {bo}, раздел "xref:backoffice:admin:system-settings.adoc#signature-cypher[Подписи и шифрование]".
====

[#non-qualifcated]
== Использование неквалифицированных сертификатов

.Требования к клиентским рабочим местам:
. Операционная система: Windows или Mac OS.
. Веб-браузер: Google Chrome, Яндекс.Браузер или Microsoft Edge на Chromium (поддерживаемые версии см. в пункте xref:requirements-software.adoc[Необходимое программное обеспечение]).
. КриптоПро ЭЦП Browser plug-in версии {sign-plugin}. https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/390[Ссылка для загрузки].
// (https://www.cryptopro.ru/products/cades/plugin[Ссылка для загрузки]).
. Неквалифицированный сертификат пользователя. Сертификат должен быть установлен в хранилище _Личное_ на уровне _Текущий пользователь_.
. Приложение КриптоПро https://www.cryptopro.ru/products/mydss2#law[myDSS 2.0] или https://www.cryptopro.ru/products/dss/mobile/dssclient[DSS Client] для работы с подписью xref:user:docs-sign.adoc#mobile[на мобильных устройствах]. Приложения обладают схожей функциональностью, рекомендуется использовать DSS Client как официальное приложение КриптоПро.

[#qualified]
== Использование квалифицированных сертификатов

.Требования к серверу:
. КриптоПро CSP версии {csp-v}.
// . https://www.cryptopro.ru/downloads[КриптоПро CADESCOM версия {cades}].
. https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/390[КриптоПро CADESCOM версия {cades}]
. {root-cert} Сертификат должен быть установлен в хранилище _Доверенные корневые центры сертификации_ на уровне _Локальный компьютер_.
. xref:6.1@engineer:ROOT:java-service.adoc[Криптосервис обслуживания ЭП] для проверки и формирования простой подписи и подписей CAdES-BES и CAdES-X Long Type 1.
. {root-cert} Должен быть установлен в хранилище _Доверенные корневые центры сертификации_ на уровне _Локальный компьютер_.

.Требования к клиентским рабочим местам:
. Операционная система: Windows или Mac OS (версии см. в требованиях https://www.cryptopro.ru/products/csp/compare[КриптоПро CSP].
. Веб-браузер: Google Chrome, Яндекс.Браузер или Microsoft Edge на Chromium (поддерживаемые версии см. в пункте xref:requirements-software.adoc#browser[Необходимое программное обеспечение]).

[start=3]
.Компоненты криптопровайдера КриптоПро:
. КриптоПро CSP версии {csp-v}.
. xref:user:prepare-add-components.adoc#cryptoPro[КриптоПро ЭЦП Browser plug-in] версии {sign-plugin}.
. CryptoPro Extension for CAdES Browser Plug-in версии {chrome-ext} (https://chrome.google.com/webstore/detail/cryptopro-extension-for-c/iifchhfnnmpdbibifmljnfjhpififfog[ссылка для загрузки]).
. КриптоПро TSPCOM версии {tspcom-v} -- компонент необходим для создания усиленной подписи Cades-X-Long-Type-1.
. См. также xref:backoffice::requirements.adoc#crypto-pro[требования для модуля "{bo}"].
. Квалифицированный сертификат пользователя. Должен быть установлен в хранилище _Личное_ на уровне _Текущий пользователь_.
+
// tag::macOS[]
NOTE: Шаги, необходимые для настройки КриптоПро в ОС Mac OS можно найти в https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/232/0/rbot-s-kriptopro-csp-v-macos[документации КриптоПро].
// end::macOS[]
+
****
// tag::expiredCryptoPro[]
Если лицензия на компоненты КриптоПро CSP истекла, добавление новых подписей блокируется. Если подпись была добавлена ранее и срок действия сертификата ЭП не истёк, возможность проверки такой подписи не будет заблокирована. Проверка старых подписей выполняется успешно в любом случае.
// end::expiredCryptoPro[]

По вопросам получения компонентов криптопровайдера КриптоПро следует обращаться в компанию ООО "КРИПТО-ПРО".
****
