= Уровень подготовки пользователя

== Пользователи модуля {wc}

.Пользователи модуля {wc} должны:
* Обладать навыками работы с xref:requirements-software.adoc#browser[веб-браузерами].
* Свободно осуществлять базовые операции в операционной системе клиентского устройства.
* Обладать знаниями предметной области.
* Обладать навыками работы с модулем _{wincl}_, а также с другими модулями и приложениями, которые установлены в системе {dv} (желательно).
* Пройти обучение по работе с модулем {wc}.

== Пользователи программы {kvr}

Основной обязанностью пользователя программы {kvr} является создание и настройка разметок.

.Пользователи программы должны:
* Иметь опыт работы с персональным компьютером на уровне квалифицированного пользователя.
* Предпочтительно иметь опыт написания скриптов на языке JavaScript и создания CSS стилей.

== Администраторы модуля {wc}

.Администратор {wc}а должен:
* Обладать навыками администрирования операционных систем:
** Astra Linux Special Edition {l-1}.
** Astra Linux Special Edition {l-1-1}.
+
include::partial$excerpts.adoc[tags=preview]
+
// ** Microsoft Windows Server {serv-3}.
// ** Microsoft Windows Server {serv-2}.
// ** Microsoft Windows Server {serv-1}.
* Иметь опыт работы с файлами `.json`, а также обладать достаточным знанием командной строки для запуска требуемых компонентов.
* Должен уметь установить и настроить необходимое ПО, указанное в разделе xref:requirements-signature.adoc[].
* Быть способным распространить на клиентские рабочие места настройки адреса и порта, используемые модулем {wc}.
* Обладать навыками администрирования модуля _{wincl}_ и других модулей и приложений, установленных в системе {dv} (желательно).

== Разработчики расширений для {wc}

.Для успешной разработки Решений на {wc}е необходимо:
* Обладать опытом разработки на языках TypeScript и C#.
* Обладать навыками разработки веб-приложений с использованием библиотеки https://reactjs.org/[React].
* Иметь опыт разработки Решений на платформе {dv} (желательно).
