= Работа с машиночитаемой доверенностью

Данный пример содержит методы работы с МЧД через API {wc}а.

.Перечень необходимых инструментов:
* Visual Studio 2017/2019
* NodeJS v14.17.0+

[#description]
== Описание примера

.Пример включает два компонента:
* `PowersOfAttorneyServerExtension` -- папка с серверным расширением Web-клиента, в котором реализованы функции создания СКД из демонстрационной карточки доверенностей.
* `PowersOfAttorneyWebExtension` -- папка с клиентским расширением, в котором реализованы обработчики смены состояния ПКД и управления МЧД, видимостью и обязательностью полей.
* `PowersOfAttorneySolution.zip` -- архив с решением, включающим разметки тестовой карточки доверенности.
* `PowersOfAttorneyCardsMetadata.zip` -- архив с данными карточек, добавляющие в систему новые виды карточки _Документ_ (_Доверенность_ и _Передоверие_) и необходимые расширенные метаданные.

== Сборка проекта

[lowerroman]
. Сборка серверной части.
[arabic]
.. Откройте решение `Samples.sln`
.. Соберите проект menu:Other[PowersOfAttorney > PowersOfAttorneyServerExtension].
. Сборка клиентской части.
[arabic]
.. Откройте в командной строке папку menu:Others[PowersOfAttorney > PowersOfAttorneyWebExtension].
.. Выполните команды:
+
 $ npm install
 $ npm update
 $ npm run build:prod
+
. Публикация компонентов на сервере Web-клиент.
[arabic]
.. Скопируйте папку `SamplesOutput\Site\Content\Modules\PowersOfAttorneyWebExtension\` в  `Каталог-установки-{wc}а\Site\Content\Modules`.
.. Скопируйте папку `SamplesOutput\Site\Extensions\PowersOfAttorneyServerExtension` в  `Каталог-установки-{wc}а\Site\Extensions`.
. Перезапустите IIS.

[#check]
== Проверка примера

. Распакуйте `PowersOfAttorneyCardsMetadata.zip` и импортируйте данные из архива в систему {dv}.
. Распакуйте `PowersOfAttorneySolution.zip`, запустите {kvr} и импортируйте решение `Solution.xml`.
. В {wc}е создайте карточку документ вида _Доверенность_. Заполните обязательные поля. +
Если заполнены не все обязательные поля, при сохранении будет выдано предупреждение.
+
.Чтобы создать свою разметку, необходимо:
* Использовать инструкцию web-расширения `ShowRequiredFields` для отображения в модальном окне незаполненных обязательных полей.
* Добавить скрипт `customizePowerOfAttorneyCardForEditLayout` в качестве обработчика события `*После загрузки всех ЭУ*` для root во всех разметках создания и редактирования карточки доверенности.
* Добавить скрипт `customizePowerOfAttorneyCardForViewCard` в качестве обработчика события `*После загрузки всех ЭУ*` для root во всех разметках просмотра карточки доверенности.
* Добавить скрипт `customizeSubstitutionPowerOfAttorneyCardForEditLayout` `*После загрузки всех ЭУ*` для root во всех разметках просмотра карточки передоверия.
* Добавить скрипт `customizeSubstitutionPowerOfAttorneyCardForViewLayout` в качестве обработчика события `*После загрузки всех ЭУ*` для root во всех разметках просмотра карточки передоверия.
. Нажмите кнопку создания МЧД. В результате будет создана МЧД, связанная с текущей карточкой документа.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт `createPowerOfAttorney` в качестве обработчика события `*При щелчке*` для кнопки в разметке просмотра карточки доверенности.
* Добавить скрипт `createRetrustPowerOfAttorney` в качестве обработчика события `*При щелчке*` для кнопки в разметке просмотра карточки передоверия.
+
. Нажмите кнопку экспорта МЧД. На компьютер будет сохранён архив, содержащий файл МЧД в формате XML.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт `exportPowerOfAttorneyWithoutSignature` в качестве обработчика события `*При щелчке*` для кнопки в разметке просмотра карточки доверенности и передоверия.
+
. Нажмите кнопку подписания МЧД. Будет предложено выбрать сертификат подписи, выполнится подписание МЧД.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт `signPowerOfAttorney` в качестве обработчика события `*При щелчке*` для кнопки в разметки просмотра карточки доверенности и передоверия.
+
. Нажмите кнопку экспорта МЧД. На компьютер будет сохранён архив, содержащий файл МЧД в формате XML и его подпись.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт `exportPowerOfAttorneyWithSignature` в качестве обработчика события `*При щелчке*` для кнопки в разметки просмотра карточки доверенности и передоверия.
+
. Нажмите кнопку отзыва МЧД.
+
Демонстрационная карточка будет переходить в состояние `Отозвана`.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт `revokePowerOfAttorney` в качестве обработчика события `*При щелчке*` для кнопки в разметки просмотра карточки доверенности и передоверия.
+
. Нажмите кнопку удаления пользовательской карточки доверенности.
+
Из пользовательской карточки доверенности также удаляется системная карточка доверенности.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт  deletePowerOfAttorney в качестве обработка события `*Перед удалением карточки*` для root.

[#api]
== API для работы с МЧД

Для работы с МЧД можно использовать перечисленные ниже классы API.

* В `DocsVision.BackOffice.Cards.Web.Model` добавлены новые для работы с машиночитаемыми доверенностями:
+
** `CreatePowerOfAttorneyFnsDovBbRequest` с полями:
*** `PowerOfAttorneyFnsDovBbData powerOfAttorneyData` -- данные создаваемой доверенности.
*** `Guid representative` -- представитель.
*** `Guid signer` -- подписант.
*** `Guid parentPowerOfAttorney` -- идентификатор родительской доверенности.
** `SignPowerOfAttorneyRequest` с полями:
*** `Guid PowerOfAttorneyId` -- идентификатор доверенности.
*** `byte[] Signature` -- данные подписи.
* В контроллер `PowerOfAttorneyApiController` добавлены новые методы:
** `POST CreatePowerOfAttorney(CreatePowerOfAttorneyFNSDOVBBRequest request)` -- вызывает `IPowerOfAttorneyService.CreatePowerOfAttorney` (создание доверенности) с передачей полей из `CreatePowerOfAttorneyFNSDOVBBRequest`.
** `GET GetMachineReadablePowerOfAttorney(Guid powerOfAttorneyId)` -- возвращает МЧД доверенности для подписания.
** `POST AttachSignatureToPowerOfAttorney(AttachSignatureToPowerOfAttorneyRequest)` -- вызывает `IPowerOfAttorneyService.AttachSignature`, загружающий подпись в существующую доверенность и изменяющий статус доверенности.

Подробнее про использование API для работы с МЧД можно узнать из описания REST API, см. раздел "xref:how-to-use-rest.adoc[]".
