= Работа с машиночитаемой доверенностью

Данный пример содержит методы работы с МЧД для {wc}а и для {wincl}а.

.Перечень необходимых инструментов:
* Visual Studio 2017/2019
* NodeJS v14.17.0+

[#description]
== Описание примера

.Пример включает компоненты:
* menu:PowersOfAttorney[PowersOfAttorneyServerExtension] -- папка с серверным расширением Web-клиента, в котором реализованы функции создания СКД из демонстрационной карточки доверенностей.
* menu:PowersOfAttorney[PowersOfAttorneyWebExtension] -- папка с клиентским расширением, в котором реализованы обработчики смены состояния ПКД и управления МЧД, видимостью и обязательностью полей.
* menu:PowersOfAttorney[PowersOfAttorney.UserCard.Common] -- папка с проектом `PowersOfAttorney.UserCard.Common`, который используется и для {wc}а и для {wincl}а.
* menu:PowersOfAttorney[PowersOfAttorney.Scripts] -- содержит файл скрипта для Windows клиента.
* menu:PowersOfAttorney[Data > PowersOfAttorneySolution] -- папка с решением, включающим разметки тестовой карточки доверенности.
* menu:PowersOfAttorney[Data > SolutionOfPOA.sol] -- решение, добавляющее в систему {dv} новые виды карточки _Документ_ (_Доверенность_ и _Передоверие_) и необходимые расширенные метаданные.

[#assembly]
== Сборка проекта

[lowerroman]
. Сборка серверной части.
[arabic]
.. Откройте решение menu:PowersOfAttorney[PowersOfAttorneyServerExtension.sln].
.. Соберите проект `PowersOfAttorneyServerExtension`.
. Сборка клиентской части.
[arabic]
.. Откройте в командной строке папку menu:PowersOfAttorney[PowersOfAttorneyWebExtension].
.. Выполните команды:
+
 $ npm install
 $ npm update
 $ npm run build:prod
+
. Публикация компонентов на сервере Web-клиент.
[arabic]
.. Скопируйте папку `SamplesOutput\Site\Content\Modules\PowersOfAttorneyWebExtension\` в  `Каталог-установки-{wc}а\Site\Content\Modules`.
.. Скопируйте папку `SamplesOutput\Site\Extensions\PowersOfAttorneyServerExtension` в  `Каталог-установки-{wc}а\Site\Extensions`.
. Перезапустите IIS.

[#check]
== Проверка примера

WARNING: Для проверки примера требуется установить версию Backoffice и Web-клиент с поддержкой СКД.

. В Менеджере Решений импортируйте решение _Машиночитаемая доверенность_ -- `PowersOfAttorney\Data\SolutionOfPOA.sol`. Рекомендуется использовать версию Менеджера решений - 5.5.3494.33 и выше.
+
.Компоненты данного решения:
* Справочник видов:
** _Документ_ -- _МЧД Доверенность (версия 002)_, _Передоверие (версия 002)_, _Доверенность (версия EMCHD_1)_, Передоверие (версия EMHCD_1).
// , _Передоверие (версия EMCHD_1)_.
** _Задание_ -- _Задание КС_ -- _На подписание МЧД_, _На согласование МЧД_.
* Метаданные: Полномочия, МЧД формат единой формы, Текстовые полномочия (а также все подчиненные).
* Конструктор правил нумерации: МЧД.
* Поиск: МЧД (МЧД все, МЧД действующие, МЧД – я автор, МЧД  – я подписант, МЧД отозванные, МЧД мои, Поиск МЧД)
* Представление: МЧД -> МЧД единого формата - представление
* Папка _Доверенность_ для хранения маршрутов согласования и подчиненные папки для работы с доверенностями.
* Согласование: маршрут "согласование и подписание МЧД единого формата" - согласование настроено на группу юридического отдела (справочник сотрудников), подписание настроено на группу генеральные директора (справочник сотрудников). Согласование параллельное, без ограничений по времени. Можно убрать участников при отправке на согласование.
+
// NOTE: Обратите внимание, что импорт решения может занять длительное время, примерно 1 час.
// +
. В справочнике видов (тип: _Согласование_, вид: _Усовершенствованное согласование_) настройте согласование для видов карточек МЧД. В окне _Настройка способа создания карточки_ выберите шаблон _Согласование и подписание МЧД единый формат_.
. В программе {kvr} импортируйте решение _Машиночитаемая доверенность_. Для этого выберите файл `Solution.xml` в папке решения `PowersOfAttorney\Data\PowersOfAttorneySolution\`.
. Проверьте, что в Справочнике сотрудников заполнены поля для участников МЧД как описано в xref:user:directories/staff/employee-fields.adoc#attorney[пользовательской документации].
. В {wc}е создайте карточку документ вида _Доверенность (версия 002)_. Заполните обязательные поля. +
Если заполнены не все обязательные поля, при сохранении будет выдано предупреждение.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт для отображения в модальном окне незаполненных обязательных полей `showRequiredFields` в качестве обработчика события `*Перед сохранением карточки*` `root` для разметок создания и/или редактирования в конструкторе разметок.
* Добавить скрипт `customizePowerOfAttorneyCardForEditLayout` в качестве обработчика события `*После загрузки всех ЭУ*` для root во всех разметках создания и редактирования карточки доверенности.
* Добавить скрипт `customizePowerOfAttorneyCardForViewCard` в качестве обработчика события `*После загрузки всех ЭУ*` для root во всех разметках просмотра карточки доверенности.
* Добавить скрипт `customizeSubstitutionPowerOfAttorneyCardForEditLayout` `*После загрузки всех ЭУ*` для root во всех разметках просмотра карточки передоверия.
* Добавить скрипт `customizeSubstitutionPowerOfAttorneyCardForViewLayout` в качестве обработчика события `*После загрузки всех ЭУ*` для root во всех разметках просмотра карточки передоверия.
+
. В {wc}е создайте карточку документ вида _Доверенность (версия EMCHD_1)_. Заполните обязательные поля. Если заполнены не все обязательные поля, при сохранении будет выдано предупреждение.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт для отображения в модальном окне незаполненных обязательных полей `showRequiredFields` в качестве обработчика события `*Перед сохранением карточки*` `root` для разметок создания и/или редактирования в конструкторе разметок.
* Добавить скрипт `customizeSingleFormatPowerOfAttorneyForEditLayout` в качестве обработчика события `*После загрузки всех ЭУ*` `root` для разметок создания и редактирования карточки доверенности в конструкторе разметок.
// * Добавить скрипт `customizeSingleFormatPowerOfAttorneyForViewLayout` в качестве обработчика события `*После загрузки всех ЭУ*` `root` для разметок просмотра, описания и справки карточки доверенности в конструкторе разметок.
* Добавить скрипт `customizeSingleFormatSPOACardForEditLayout` в качестве обработчика события `*После загрузки всех ЭУ*` `root` для разметок создания и редактирования карточки передоверия в конструкторе разметок.
* Добавить скрипт `customizeSingleFormatSPOACardForViewLayout` в качестве обработчика события `*После загрузки всех ЭУ*` `root` для разметок просмотра, описания и справки карточки передоверия в конструкторе разметок.
* Добавить скрипт `customizeSingleFormatSPOACardForViewLayout` в качестве обработчика события `*После загрузки всех ЭУ*` `root` для разметок просмотра, описания и справки карточки передоверия в конструкторе разметок.
+
. Нажмите кнопку создания МЧД. В результате будет создана МЧД, связанная с текущей карточкой документа.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт `createPowerOfAttorney` в качестве обработчика события `*При щелчке*` для кнопки в разметке просмотра карточки доверенности.
* Добавить скрипт `createRetrustPowerOfAttorney` в качестве обработчика события `*При щелчке*` для кнопки в разметке просмотра карточки передоверия (версия 002).
// * Добавить скрипт `createEMCHDPowerOfAttorney` в качестве обработчика события `*При щелчке*` для кнопки для разметок просмотра карточки доверенности (версия EMCHD_1) в конструкторе разметок.
* Добавить скрипт `createEMCHDRetrustPowerOfAttorney` в качестве обработчика события `*При щелчке*` на кнопку для разметок просмотра карточки передоверия (версия EMCHD_1) в конструкторе разметок.
* Добавить скрипт `createEMCHDPowerOfAttorney` в качестве обработчика события `*При щелчке*` на кнопку для разметок просмотра карточки доверенности (версия EMCHD_1) в конструкторе разметок.
* Добавить скрипт `createEMCHDRetrustPowerOfAttorney` в качестве обработчика события `*При щелчке*` на кнопку для разметок просмотра карточки передоверия (версия EMCHD_1) в конструкторе разметок.
+
. Нажмите кнопку экспорта МЧД. На компьютер будет сохранён архив, содержащий файл МЧД в формате XML.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт `exportPowerOfAttorneyWithoutSignature` в качестве обработчика события `*При щелчке*` для кнопки в разметке просмотра карточки доверенности и передоверия.
+
. Нажмите кнопку подписания МЧД. Будет предложено выбрать сертификат подписи, выполнится подписание МЧД.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт `signPowerOfAttorney` в качестве обработчика события `*При щелчке*` для кнопки в разметки просмотра карточки доверенности и передоверия.
+
Для подписания и последующей регистрации доверенности по файлу нужно добавить скрипт `signAndSendPowerOfAttorneyToRegistrationAsFile` в качестве обработчика события `*При щелчке*` на кнопку для разметки просмотра карточки доверенности.
+
. Нажмите кнопку экспорта МЧД. На компьютер будет сохранён архив, содержащий файл МЧД в формате XML и его подпись.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт `exportPowerOfAttorneyWithSignature` в качестве обработчика события `*При щелчке*` для кнопки в разметки просмотра карточки доверенности и передоверия.
+
. Нажмите кнопку отзыва МЧД.
+
* Для доверенности и передоверия (версия 002) появится окно заявления на отзыв, после заполнения которого появится окно с возможностью подписать сформированное заявление на отзыв, затем демокарточка будет переходить в состояние _Отозвана_.
+
--
.Чтобы создать свою разметку, необходимо:
** Добавить скрипт `revokePowerOfAttorney` в качестве обработчика события `*При щелчке*` на кнопку для разметки просмотра карточки доверенности и передоверия (версия 002) в конструкторе разметок.
--
+
* Для доверенности и передоверия (версия EMCHD_1) демокарточка будет переходить в состояние _Отозвана_.
+
--
.Чтобы создать свою разметку, необходимо:
** Добавить скрипт `revokePowerOfAttorneyWithoutApplication` в качестве обработчика события `*При щелчке*` на кнопку для разметки просмотра карточки доверенности и передоверия (версия EMCHD_1) в конструкторе разметок.
--
+
. Нажмите кнопку экспорта заявления на отзыв для доверенности и передоверия (версия 002). На компьютер будет сохранён архив, содержащий файл заявления на отзыв в формате XML и его подпись.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт `exportApplicationForRevocation` в качестве обработчика события `*При щелчке*` на кнопку для разметки просмотра карточки доверенности (версия 002) и передоверия (версия 002) в конструкторе разметок.
+
. Нажмите кнопку удаления пользовательской карточки доверенности.
+
Из пользовательской карточки доверенности также удаляется системная карточка доверенности.
+
.Чтобы создать свою разметку, необходимо:
* Добавить скрипт `deletePowerOfAttorney` в качестве обработчика события `*Перед удалением карточки*` для `root`.
+
. Доверенность можно подписать в ходе согласования.
+
.Чтобы подписать доверенность в ходе согласования, необходимо:
* Отправить Доверенность на согласование как описано в _Инструкции пользователя_.
* Нажать кнопку *Подписать* в _Задании_. В результате сформируется СКД, затем подпишется доверенность, ПКД перейдет в статус `Подписана`, а задание перейдет в статус `Завершено`.
* Для создания своей разметки нужно добавить скрипт `signAndSendPowerOfAttorneyToRegistrationAsFileFromTask` в качестве обработчика события `Перед выполнением операции` на ЭУ `_Автомат состояния_` для подписания и последующей регистрации доверенности по файлу. +
Для подписания без регистрации используйте скрипт `signPowerOfAttorneyFromTask`.

[#winclient-scripts]
== Пример скриптов для Windows клиента

. Скрипт находится в файле `CardDocumentДоверенность__версия_EMHCD_1_Script.cs` в проекте `PowersOfAttorney.Scripts`
. Проект нужен только для проверки компилируемости скрипта. Ссылки на сборку `PowersOfAttorney.Scripts.dll` добавлять не надо.
. Скрипт необходимо скопировать в справочник скриптов для двух видов (для доверенности EMHCD и передоверия EMHCD). Если у родительского вида для этих видов нет скрипта, надо открыть его и сгенерировать для него скрипт по-умолчанию.
. Необходимо закомментировать в файле скрипта для обоих видов строчку
+
 using CardDocumentМЧДScript = DocsVision.BackOffice.WinForms.ScriptClassBase;
+
Строка нужна только для компиляции файла скрипта в составе проекта `PowersOfAttorney.Scripts`.
+
. Скрипты для этих видов отличаются только названиями классов. Необходимо для каждого вида оставить только одно соответствующее ему название класса (см. комментарий в скрипте).
. В  скриптах необходимо добавить ссылку на сборку `PowersOfAttorney.UserCard.Common.dll`.
. В конструкторе разметок необходимо добавить кнопки (например в ленту). Названия кнопок должны соответствовать обработчикам в скрипте.
+
В скрипте обработчики выглядят как `имяКнопки__ItemClick();` Если названия кнопки будут соответствовать обработчикам, то обработчики к кнопкам привяжутся автоматически, вручную их создавать не надо.
+
. Можно привязать к кнопкам соответствующие операции, чтобы кнопки были доступны только в тех состояниях, когда их нажатие имеет смысл.

[#api]
== API для работы с МЧД

Для работы с МЧД можно использовать перечисленные ниже классы API.

* В `DocsVision.BackOffice.Cards.Web.Model` добавлены новые для работы с машиночитаемыми доверенностями:
+
** `CreatePowerOfAttorneyFnsDovBbRequest` с полями:
*** `PowerOfAttorneyFnsDovBbData powerOfAttorneyData` -- данные создаваемой доверенности.
*** `Guid representative` -- представитель.
*** `Guid signer` -- подписант.
*** `Guid parentPowerOfAttorney` -- идентификатор родительской доверенности.
** `SignPowerOfAttorneyRequest` с полями:
*** `Guid PowerOfAttorneyId` -- идентификатор доверенности.
*** `byte[] Signature` -- данные подписи.
* В контроллер `PowerOfAttorneyApiController` добавлены новые методы:
** `POST CreatePowerOfAttorney(CreatePowerOfAttorneyFNSDOVBBRequest request)` -- вызывает `IPowerOfAttorneyService.CreatePowerOfAttorney` (создание доверенности) с передачей полей из `CreatePowerOfAttorneyFNSDOVBBRequest`.
** `GET GetMachineReadablePowerOfAttorney(Guid powerOfAttorneyId)` -- возвращает МЧД доверенности для подписания.
** `POST AttachSignatureToPowerOfAttorney(AttachSignatureToPowerOfAttorneyRequest)` -- вызывает `IPowerOfAttorneyService.AttachSignature`, загружающий подпись в существующую доверенность и изменяющий статус доверенности.

Подробнее про использование API для работы с МЧД можно узнать из описания REST API, см. раздел "xref:how-to-use-rest.adoc[]".
