= Пример расширения Службы {ws}

Демонстрационный вариант расширения Службы {ws}, расположенный в https://github.com/Docsvision/WebClient-Samples/tree/master_net45/Others/SampleWorkerExtension[репозитории {dv} на GitHub]. Расширение получает ID карточки документа и конвертирует приложенные файлы в формат PDF/A.

.Перечень необходимых инструментов:
* Visual Studio 2017/2019

== Сборка

. Откройте `/Samples.sln`.
. [[above]]Соберите проект `Others > SampleWorkerExtension`.
. Соберите проект `Samples\Others\SampleWorkerExtension\SampleWorkerExtension.WebClientExtension\SampleWorkerExtension.WebExtension`.
. Выполните `npm i`, `npm run build`.
. Соберите пример xref:server/conversion-sample.adoc[взаимодействия с сервисом конвертации].

== Установка

. Отправьте в GAC сборки, полученные в пункте 2 <<above,выше>>.
+
 gacutil.exe -if DocsVision.SampleWorkerExtension.Manager.dll
 gacutil.exe -if DocsVision.SampleWorkerExtension.ObjectModel.dll
 gacutil.exe -if DocsVision.SampleWorkerExtension.WorkerService.dll
 gacutil.exe -if ru\DocsVision.SampleWorkerExtension.WorkerService.resources.dll
+
. Добавьте сборки `DocsVision.SampleWorkerExtension.Role.dll` вместе с ресурсами `ru\DocsVision.SampleWorkerExtension.Role.resources.dll` и конфигурационный файл `SampleWorkerExtension.json` (находится в проекте `SampleWorkerExtension.Role`) в папку {of-mc}. +
Если папка с расширениями отсутствует, создайте вручную. Например, `C:\Program Files (x86)\Docsvision\ManagementConsole\SampleExtensions`.
. Добавьте сборку `DocsVision.SampleWorkerExtension.WorkerExtension.dll` в папку `WorkerService`. Например, `C:\Program Files (x86)\Docsvision\WorkerService\5.5\Extensions`.
. Установите серверное и клиентское расширения для {wc}а, которые находятся в `Others\SampleWorkerExtension\SampleWorkerExtension.WebClientExtension` (инструкция внутри проекта).
. Установите пример xref:server/conversion-sample.adoc[взаимодействия с сервисом конвертации].
. Отредактируйте конфигурационный файл Сервиса внешнего API {of-mc} по адресу `C:\Program Files (x86)\Docsvision\ManagementConsoleExternalAPI\DocsVision.ManagementConsole.ExternalAPI.WindowsService.exe.config`.
+
. В секцию `Libraries` конфигурационного файла добавьте строку, содержащую `SampleWorkerExtension.WorkerService` следующим образом:
+
[source,html]
----
<Libraries>
  <add Path="DocsVision.BackOffice.ObjectModel, Version=5.5.0.0, Culture=neutral, PublicKeyToken=7148afe997f90519" />
  <add Path="DocsVision.SampleWorkerExtension.WorkerService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=4a2caa47aa5b6b29" />
</Libraries>
----

== Проверка

. Откройте {mc} и создайте xref:5.5.1@mgmtconsole:user:worker-service.adoc[новый процесс] Службы {ws} с типом конфигурации *_Расширение_* для WorkerService.
. В разметке документа {wc}а (например, просмотр) создайте кнопку и добавьте для события `*При щелчке*` обработчик `sendConversionTask`.
. В {wc}е создайте документ и приложите к нему файлы. Сохраните документ и в открывшейся разметке нажмите созданную кнопку. Через некоторое время в секции файлов появятся файлы, конвертированные в формат PDF/A.

== Проект "SampleWorkerExtension"

Проект содержит создание сообщения для Службы {ws} в серверном расширении `SampleWorkerExtension.ServerExtension` и расширении {wc}а `SampleWorkerExtension.WebExtension`.

Проект-расширение для {wc}а `SampleWorkerExtension.ServerExtension` содержит скрипт для создания сообщения для Службы {ws}. Проект демонстрирует расширение функционала с помощью добавления новых сервисов, контроллеров. Реализован контроллер `SampleWorkerController` с методом `SendToWorker`, который вызывает сервис `ISampleWorkerService`. В сервисе осуществляется создание сообщения для Службы {ws} с переданным идентификатором карточки, откуда был вызван скрипт.

== Проект "SampleWorkerExtension.WebClientServerExtension"

Проект содержит клиентские скрипты, в которых при нажатии на кнопку с помощью сервиса `requestManager` отправляется запрос на сервер. После конвертации файла в `.pdf`, он отображается в карточке.

== Разработка

При разработке собственного расширения необходимо дорабатывать или переписывать класс:

[source,csharp]
----
public class SampleEventHandlerService : EventHandlerService, ISampleEventHandlerService
----

При создании собственных событий будет реализовываться управление обработкой событий:

[source,csharp]
----
  public static readonly EventDescription ConvertCardFiles = new EventDescription { Id = new Guid("B2C6F070-C7F1-4F07-914F-94652804DD1C"), AutoSendToSelf = true, Concurrent = false };

        private readonly Dictionary<Guid, EventHandlerInfo> handlersInfo = new Dictionary<Guid, EventHandlerInfo>
        {
            {
                ConvertCardFiles.Id,
                new EventHandlerInfo
                    { EventId = ConvertCardFiles.Id, EventArgsType = typeof(SampleEventArgs), EventHandlerName = nameof(ProcessCardFiles) }
            }
        };
----

Также при доработке компонента логики будет реализована своя логика обработки этих событий:

[source,csharp]
----
private const string SampleComponentTypeName = "SampleWorkerExtension.Manager.SampleApiManager, SampleWorkerExtension.Manager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=4a2caa47aa5b6b29";
----
