= Изменить режим работы с Решением

Режим работы с Решением определяет возможность изменения разметок, условий выбора и других настроек Решения. {kvr} поддерживает два режима:

* _Заказчик_. Изменение Решения заблокировано.
* _Поставщик_. Изменение Решения разрешено.

.Чтобы изменить режим работы с Решением:
. Откройте xref:solutions-control-panel.adoc[Панель управления Решениями].
. Выберите Решение, режим которого нужно изменить.
. Нажмите кнопку *Переключить режим*. Режим изменится на противоположный.
+
[WARNING]
====
* Запрещено изменять настройки стандартных Решений {wc}а: _Базовое решение_ и _Управления документами_. При необходимости выполните xref:solutions-edit-standard.adoc[следующие шаги].
* После установки Решения в рабочую базу данных не рекомендуется изменять его режим работы на _Поставщик_, т. к. это может привести к ошибкам при обновлении Решения.
====

== Отобразить кнопку "Переключить режим"

Кнопка *Переключить режим* по умолчанию недоступна. Чтобы её отобразить выполните следующие действия:

. Откройте конфигурационный файл `C:/Program Files (x86)/Docsvision/WebClient/WebLayoutsDesigner.appsettings.json`.
. Измените значение настройки menu:{dv}[WebClient > SettingGroups > WebLayoutsDesigner > DesignerMode] на значение:
+
* `Vendor`, чтобы разрешить изменять режим Решения.
* `Customer`, чтобы запретить изменять режим Решения.
+
. Запустите {kvr} и откройте xref:solutions-control-panel.adoc[Панель управления Решениями].
. Выберите Решение в списке и нажмите кнопку *Переключить режим*. Значение режима будет изменено.
