= Стандартные web-сервисы

В данном разделе рассмотрены основы работы с сервисами, а также основные web-сервисы, доступные для использования в web-расширениях.

[#current]
== Сервисы информации о текущей карточке/строке/разметке

Информацию о текущей разметке можно получить с помощью следующих сервисов:

* `$CardId` -- идентификатор текущей карточки текущей разметки.
* `$RowId` -- идентификатор текущей строки текущей разметки (если открыта разметка строки, а не карточки)
* `$CardTimestamp` -- `timestamp` текущей карточки текущей разметки.
* `$CardInfo` -- дополнительная информация о текущей карточке, текущей разметки. Например, там можно найти тип и вид карточки, ее состояние и другие данные.
* `$RowInfo` -- дополнительная информация о текущей строке, текущей разметки (если открыта разметка строки).
* `$LayoutInfo` -- дополнительная информация о текущей разметке.
* `$Layout` -- экземпляр текущей разметки. Содержит множество различных методов, среди которых сохранение (`save`), перезагрузка (`reloadFromServer`), смены состояния карточки (`changeState`) и другие.
* `$ControlStore` -- предоставляет доступ к элементам управления на разметке по имени через методы `get` и `tryGet`. Первый метод генерирует ошибку, в случае отсутствия элемента управления с таким именем, второй просто возвращает `null`.
* `$EditOperationStore` -- позволяет получить информацию о доступности операции редактирования.

[#environment]
== Сервисы информации об окружении

Информацию в целом о текущем контексте работы приложения можно с помощью следующих сервисов:

* `$CurrentEmployeeId` -- идентификатор текущего пользователя.
* `$CurrentEmployeeAccountName` -- имя учетной записи текущего пользователя.
* `$CurrentEmployee` -- расширенная информация о текущем пользователе. Состав полей можно найти в описании типа `CurrentEmployeeInfo`.
* `$ApplicationTimestamp` -- строка, изменяющаяся при перезапуске веб-сервиса.
* `$ApplicationSettings` -- системные настройки (см. `GenModels.ApplicationSettings`).
* `$Locale` -- двухбуквенное обозначение текущей выбранной локализации веб-клиента (например: `ru`, `en`).
* `$CurrentFolder` -- информация о текущей открытой папке (см. `ICurrentFolderService`).
* `$DeviceType` -- обозначение текущего выбранного типа устройства (компьютер/телефон/планшет). См. `GenModels.DeviceType`.
