= Пример текста

Данный раздел содержит описание примера реализации элемента управления `_HyperComments_`.

WARNING: Платформа `HyperComments` перестала поддерживать бесплатный тариф. Необходимо приобретение лицензии.

Пример требует подключенного расширения программы {kvr} `UrlProprtyDesignerExtension`.

include::ROOT:partial$excerpts.adoc[tags=wc-node]
include::ROOT:partial$excerpts.adoc[tags=vscode]

== Проект "HyperCommentsWebExtension"

Проект-расширение клиентской части {wc}а. Содержит пример одного из способов интеграции со сторонними веб-приложениями.

== Проект "HyperCommentsDesignerExtension"

Проект-расширение для конструктора разметок. Содержит описание элемента управления `HyperComments` для программы {kvr}.
Демонстрирует описание и подключение нового ЭУ, используя класс `ControlTypeDescription`,
задание ему стандартных свойств, реализованных в  программе {kvr}footnote:[См. `PropertyFactory.GetNameProperty()`] и
добавление собственного свойства, используя `PropretyDescription`, классfootnote:[См. свойство `WidgetId`].

== Сборка и установка

. Откройте `/Samples.sln`.
. Соберите проект `Controls > HyperComments > HyperCommentsDesignerExtension`.
. Откройте консоль в папке `Controls > HyperComments > ExchangeRatesWebExtension` и выполните команду `npm install` и `npm run build:prod`.
. Скопируйте каталог `SamplesOutput\Plugins\HyperCommentsDesignerExtension` в каталог `Путь к директории с исполняемым файлом конструктора Web-разметок\Plugins`.
. Скопируйте каталог `SamplesOutput\Content\Modules\HyperCommentsWebExtension` в каталог `Путь к сайту {wc}а\Content\Modules`.
. Перезапустите *{wcs-new}*.

== Регистрация виджета "HyperComments"

. Перейдите на сайт https://www.hypercomments.com.
. Нажмите на кнопку *Войти*.
. Авторизоваться под аккаунтом Google.
. Выбрать лицензию и следовать инструкциям.
. Нажмите на кнопку *Установить*.
. Ввести адрес сайта (Допустимо имя сайта в локальной сети).
. Выбрать тип виджета - HTML Custom code.
. Нажмите *Далее*.
. Нажмите *Готово*.
. Перейдите на страницу _Виджет -- Общее_.
. [[id]]Под заголовком указан идентификатор виджета ID: `&#x23;&#x23;&#x23;&#x23;&#x23;&#x23;`, его следует запомнить, он потребуется далее.
. Установите флаг напротив настройки `*Get-параметры*`. Учитывайте GET параметры и сгенерируйте новый виджет комментирования для отдельной страницы.
. Нажмите на кнопку *Сохранить*.

== Проверка примера

. Запустите конструктор разметок.
. Скопируйте любую разметку для карточки вида _Служебная записка_.
. Выберите условия использования этой разметки.
. Откройте разметку и добавить в нее новый элемент управления `_Hyper comments_`.
. Укажите в свойстве `*Widget id*` идентификатор из <<id,пункта выше>>.
. Сохраните разметку.
. Перезапустите *{wcs-new}*.
. Откройте карточку с этой разметкой.
. Убедитесь, что появился новый элемент управления.
