= Изменить форматы для редактирования

По умолчанию {wc} предлагает возможность открывать в стороннем ПО файлы следующих форматов: `.doc`, `.docx`, `.docm`, `.xls`, `.xlsx`, `.xlsm`, `.ppt`, `.pptx`, `.odt` и `.ods`. Данная функциональность доступна только, если установлено соответствующее ПО, позволяющее открывать файлы на редактирование, а также если пользователь установил и запустил _DVWebTool_ или _DVSupService_.

При необходимости администратор может расширить список поддерживаемых форматов, которые можно будет открывать на редактирование при условии, если необходимое ПО установлено на компьютере пользователя.

NOTE: С добавленными форматами функциональность открытия на редактирование может работать некорректно.

// tag::webconfig[]
.Если нужно предоставить возможность открывать файлы определённых форматов в карточки, выполните следующую настройку:
. Откройте конфигурационный файл {wc}а по адресу `{webconfig}`.
. В параметре {cnf-sgrps-wc} > "AcceptableFileExtensionsForEditing"] измените список доступных файлов:
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "AcceptableFileExtensionsForEditing": "\\b(doc|docx|docm|xls|xlsx|xlsm|ppt|pptx|odt|ods|xodt|xods|xodp)$" <.>
        }
      }
    }
  }
----
<.> Перечислите поддерживаемые форматы в значении параметра.
+
. Если параметр `"AcceptableFileExtensionsForEditing"` не указан, по умолчанию на редактирование открываются только файлы форматов `.doc`, `.docx`, `.docm`, `.xls`, `.xlsx`, `.xlsm`, `.ppt`, `.pptx`, `.odt` и `.ods`.
// end::webconfig[]
