= Настройки очистки данных пользовательских сессий

Сервер {wc}а удаляет из своего кэша данные пользовательских сессий, которые были закрыты.

// tag::webconfig[]
.Чтобы отключить очистку кэша закрытых сессий:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {cnf-sgrps-wc}].
. Измените значение параметра `DisableClearSession`:
+
--
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "DisableClearSession": "True" <.>
        }
      }
    }
  }
----
<.> Возможные значения:
+
* `False` -- данные сессий будут очищены после закрытия.
* `True` -- значение по умолчанию, данные закрытых сессий не будут очищаться.
--
+
WARNING: При отключении функции очистки кэша также будет отключен механизм автоматического закрытия неиспользуемых сессий. См. xref:close-session-config.adoc[Настройка автоматического закрытия неактивных пользовательских сессий].
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.
