= Управление временем жизни пользовательских cookie

Управлять временем действия пользовательской сессии можно с помощью настроек в конфигурационном файле {wc}а:

// tag::webconfig[]
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "AuthCookieAutoRenewalInterval": 0 <.>
          "AuthCookieLifetime": 120 <.>
          "MobileAuthCookieLifetime": 120 <.>
        }
      }
    }
  }
----
<.> `AuthCookieAutoRenewalInterval` -- интервал автоматического обновления сессии.
<.> `AuthCookieLifetime` -- период действия пользовательской сессии.
<.> `MobileAuthCookieLifetime` -- период действия пользовательской сессии на мобильных устройствах.
// end::webconfig[]

.Принцип действия настроек:
. Настройка `AuthCookieAutoRenewalInterval` позволяет продлевать срок уже выданных cookie, если пользователь зашёл до того, как они истекли.
+
По умолчанию настройка отключена, то есть установлена в значение `0`. Можно задать количество часов.
+
Когда пользователь авторизуется в {wc}е, ему по умолчанию выдаются cookie на 5 дней. Если в настройке указано значение `24` часа, действие cookie будет продлено, когда пользователь откроет {wc}. Настройка сработает только если пользователь откроет {wc} в промежутке между указанным временем и сроком истечения сессии.
+
. Настройка `AuthCookieLifetime` устанавливает период действия пользовательской сессии. Значение по умолчанию: `120` часов (5 дней).
. Настройка `MobileAuthCookieLifetime` отдельно задаёт период действия пользовательской сессии на мобильных устройствах. Значение по умолчанию: `120` часов (5 дней).

Настройки можно комбинировать. Например, задать для `AuthCookieLifetime` значение `240` часов, чтобы все пользователи получали cookie на 10 дней. Для настройки `MobileAuthCookieLifetime` можно указать период в `720` часов (30 дней). А также установить значение `AuthCookieAutoRenewalInterval` на `72` часа. Когда пользователь откроет {wc} по прошествии трёх дней с предыдущей авторизации, cookie автоматически будут продлены.
