= Система отслеживания работоспособности счётчиков

Система отслеживания работоспособности счётчиков проверяет состояние счётчиков с периодичностью, указанной в конфигурационном файле Web-клиента по адресу `{webconfig}`.

[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "EnablePerformanceCounters": "True", <.>
          "AutoDiagnosticLogTime": 15, <.>
          "AutoDiagnosticLogEnableMinInterval": 1, <.>
          "UnreadCountersHealthCheckInterval": 10, <.>
          "UnreadCountersMonitoringSettings": [ <.>
            "UnreadCountersMonitoring": { <.>
              "TenantName": "docsvisiondb", <.>
              "GroupId": "{922C8947-A98A-45FA-A3D2-6EE71AEE13A8}",
              "RoleId": "{55165FC3-01C7-42EE-B248-06CB79DDB67A}",
              "WarnTimeout": 10, <.>
              "AlertTimeout": 20 <.>
            }
          ]
        }
      }
    }
  }
----
<.> `EnablePerformanceCounters` -- счетчики производительности включены.
<.> `AutoDiagnosticLogTime` -- период журналирования в минутах, по умолчанию 15.
<.> `AutoDiagnosticLogEnableMinInterval` -- Расширенное журналирование включается не чаще, чем раз в интервал. Интервал задаётся в часах, по умолчанию 1, можно указать дробное значение.
<.> `UnreadCountersHealthCheckInterval` -- параметр отвечает pа периодичность проверки, значение параметра задается в секундах и по умолчанию составляет 10 секунд.
<.> `UnreadCountersMonitoringSettings` -- работоспособность счётчиков проверяется для пользователей, указанных в параметре.
<.> Можно указывать группы (`RoleId`), роли (`GroupId`), а также базы данных (`TenantName`). +
Идентификаторы (RowId) для ролей и групп можно получить через DVExplorer.
+
<.> Период времени для каждой группы пользователей задается в параметрах `*WarnTimeout*` и `*AlertTimeout*`.

Если в течение периода `*WarnTimeout*` не производился расчёт счётчиков, будет выдано предупреждение. Если после периода `*AlertTimeout*` расчёт счётчиков не возобновился, будет записано сообщение об ошибке и выполнена попытка восстановить (перезапустить) работу счетчиков. Также включится уровень журналирования Trace.

Счетчики считаются рабочими, если производится расчет значений не реже чем раз в период времени, указанный в `*WarnTimeout*` и `*AlertTimeout*`. Периоды нужно подбирать в соответствии с настройками времени расчета папок, отображаемых для пользователей. Если все папки свернуты, проверка приостанавливается. Об этом отправляется информационное сообщение.

 Стоит учитывать, что если папка свернута в главном меню (не видима), то по ней не производится расчет счетчиков.

Предупреждения и ошибки выдаются однажды перед изменением состояния. То есть, если возникла ошибка, и она сохраняется, будет выдано одно сообщение. Если счетчики заработают, а потом снова перестанут, сообщение появится снова.

Предупреждение отправляется в сервис `ISystemStateNotificationService`: записываются в журнал {wc}а и выводятся в консоли браузера. Данные сообщений можно получать через внешний сервис, если подписаться на событие `ISystemStateNotificationService.Notification`. В сообщении есть поля `Severity` и `Source`, которые нужно учитывать.
