= Настройка меню создания карточек

Администратор {wc}а может изменить настройки меню создания карточек: добавить или удалить типы карточек, изменить последовательность отображения типов.

// tag::webconfig[]
.Чтобы изменить настройки меню создания карточек:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к элементу `{cnf-wc} > CardTypes]`.
. Измените параметр `CardTypeId`:
+
WARNING: {wc} поддерживает работу только с карточками, созданными на основе _Базовых объектов_.
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "CardTypes": [
        {
          "CardTypeId": "b9f7bfd7-7429-455e-a3f1-94ffb569c794", <.>
          "CssClass": "document", <.>
          "SaveInFolder": "true" <.>
        },
        {
          "CardTypeId": "c7b36f33-cdd4-4da9-8444-600fe14111e4",
          "CssClass": "task"
          "SaveInFolder": "true"
        }
      ]
    }
  }
----
<.> "CardTypeId": "GUID-идентификатор типа карточки". +
Чтобы изменить порядок кнопок создания типов карточек, измените порядок следования GUID-идентификаторов (`CardTypeId`) в `CardTypes`.
<.> Чтобы изменить цвет строки типа карточки в меню создания карточек, добавьте в элемент `CardType` параметр `CssClass` с названием класса CSS в значении.
<.> Чтобы новые карточки выбранного типа сохранялись в текущей открытой папке, добавьте в элемент `CardType` параметр `SaveInFolder` со значением `true`. +
Если `SaveInFolder` имеет значение `false` (или отсутствует), ярлыки карточек не будут добавляться в текущую папку.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.

****
Чтобы изменение цвета строки типа карточки в меню создания работало корректно, к {wc}у должен быть подключен файл стилей с CSS-классом `.Значение-атрибута-CssClass-color`:

[source,css]
----
.document-color {
    background-color: #639;
}
----
****
