= Функция "Общие справочники"

Данная функция включает особый режим работы со справочниками, данные которых используются только в режиме чтения.

Функция по умолчанию активна в {wc}е, начиная с версии 17.

Использование функции _Общие справочники_ призвано сократить потребления памяти процессом сервера {dv}.

[#change-mode]
== Изменить способ обновления справочников в режиме "только чтение"

{wc} использует справочники, данные которых только читаются и не изменяются, в режиме "только чтение". В данном режиме один справочник используется всеми сессиями и обновляется в соответствии со стратегией обновления, установленной в настройках {wc}.

Администратор может изменить режим обновления таких справочников в зависимости от требований к актуальности их данных. Увеличение частоты обновления ведёт к увеличению числа обращений с северу {dv}, а уменьшение -- к возможности получения устаревших данных.

// tag::webconfig[]
.Чтобы изменить способ обновления справочников:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {cnf-sgrps} > "System"].
. Измените значение параметра `SharedDictionaryRefreshMode`. Параметр определяет способ обновления справочников.
+
Настройки обновления справочников влияют также на обновление разметок. *На период разработки разметок* рекомендуется установить меньший период обновления.
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "SharedDictionaryRefreshMode": "0" <.>
          "SharedDictionaryRefreshPeriod": "120" <.>
        }
      }
    }
  }
----
<.> .Возможные значения:
* `0` -- обновление выполняется с интервалом, указанным в параметре `SharedDictionaryRefreshPeriod`.
* `1` -- если в одной из сессий данные справочника в режиме только чтение были изменены, обновление будет выполнено при следующем обращении.
* `2` -- если в одной из сессий данные справочника в режиме только чтение были изменены, обновление будет выполнено сразу после изменения (значение по умолчанию).
+
<.> Задать период обновления справочника равный 2 минутам.  Значение указывается в секундах, по умолчанию -- 600 секунд.
// end::webconfig[]
+
include::partial$excerpts.adoc[tags=ifabsent]
+
. Сохраните изменения конфигурационного файла.
