= Кэширование обращений к справочникам и карточкам

При обращении к справочникам и карточкам {wc} может использовать два режима обновления объектов:

* `ShortCacheRefreshPeriod` -- короткий период обновления кэша.
* `LongCacheRefreshPeriod` -- длительный период обновления кэша.

Короткий период обновления позволяет повысить производительность при обращении к справочникам и карточкам. Параметры также влияют на обновление данных в разметке профиля пользователя. Настроить поведение можно в конфигурационном файле {wc}а по пути `{webconfig}`.

// tag::webconfig[]
.Чтобы настроить период обновления, укажите значения в секундах:
[source]
----
<SettingGroup Name="System">
  <Setting Name="ShortCacheRefreshPeriod" Value="600" /> <.>
  <Setting Name="LongCacheRefreshPeriod" Value="14400" /> <.>
----
<.> Короткий период обновления кэша и данных в разметке профиля пользователя.
<.> Длительный период обновления кэша и данных в разметке профиля пользователя.

Для папок используется `ShortCacheRefreshPeriod`. `LongCacheRefreshPeriod` -- пока не используется.
// end::webconfig[]
