= Отключить создание карточек определённого типа

В случае необходимости, администратор системы может отключить возможность создания из {wc}а карточек определённого типа. Когда функция отключена, соответствующий тип карточек будет скрыт из списка доступных для создания типов карточки вместе с подвидами:

* При нажатии кнопки *+ Создать* на панели управления.
* При создании карточки с добавлением ссылки из карточек _Документ_ и _Задание_.

// tag::webconfig[]
.Чтобы скрыть тип карточки из меню создания:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к элементу {cnf-wc} > CardTypes].
+
В элементе `CardTypes` перечислены типы карточек, с которыми работает {wc}:
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "CardTypes": [
        {
          "CardTypeId": "b9f7bfd7-7429-455e-a3f1-94ffb569c794", <.>
          "CssClass": "document",
          "SaveInFolder": "true"
        },
        {
          "CardTypeId": "c7b36f33-cdd4-4da9-8444-600fe14111e4", <.>
          "CssClass": "task"
          "SaveInFolder": "true"
        },
        {
          "CardTypeId": "c7b36f33-cdd4-4da9-8444-600fe14111e4", <.>
          "CssClass": "task"
          "SaveInFolder": "true"
          "DisableCreateFlags": "0" <.>
        }
      ]
    }
  }
----
<.> Документ.
<.> Задание.
<.> Группа заданий.
<.> Создайте или измените параметр `DisableCreateFlags` в элементе нужного типа карточек. +
Значение параметра `DisableCreateFlags` является суммой цифр, каждая из которых определяет один из вариантов скрытия типа карточки:
+
* `0` -- не скрывать.
* `1` -- скрывать тип из списка типов при создании карточки при нажатии кнопки *+ Создать* на панели управления.
* `2` -- скрывать тип из списка типов при создании карточки с добавлением ссылки из карточек _Документ_ и _Задание_, а также при создании карточки в качестве отчёта к _Заданию_.
* `4` -- скрывать тип из списка типов при создании связанного задания карточки _Документ_.
* `8` -- скрывать тип из списка типов при создании подчиненного задания карточки _Задание_.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.

****
Чтобы отключить любую возможность создания карточки _Группа заданий_ из {wc}а, укажите значение *_15_* (= 1+2+4+8). Чтобы скрыть тип карточки _Документ_ из списка типов при создании новой карточки, укажите значение `1`.

WARNING: Параметр `DisableCreateFlags` не действует, когда меню создания карточки вызывается из настраиваемой разметки.
****
