= Изменить список разрешённых для добавления файлов

По умолчанию пользователь может добавлять в карточки файлы со следующими расширениямиfootnote:[Чтобы загружать файлы `.ascx`, `.cs` и `.java` требуется дополнительная настройка. См. пункт xref:install-after.adoc["Действия после установки {wc}а"].]:

include::user:partial$extensions.adoc[tags=long-ppt]

// tag::webconfig[]
Администратор может добавить в список новые расширения файлов или удалить существующие.

. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {setgroups-wc}.
. Измените значение параметра `AcceptableFileExtensions`. Значение содержит строку регулярного выражения. Новые расширения файлов нужно добавлять во вторые скобки, через символ `|`.
+
.Добавление `.dwg` в допустимые расширения:
====
[source]
----
<Setting Name="AcceptableFileExtensions" Value="(.|/)(rtf|dot|doc|dotx|ods|docx|odt|csv|xlt|xls|xltx|xlsx|xlsb|pdf|jpg|jpeg|gif|png|bmp|tiff|tif|emf|wmf|xslt|xsl|xml|htm|html|txt|log|cs|asmx|ascx|aspx|js|cpp|h|css|idl|ini|java|rc|rc2|shtm|shtml|sql|zip|rar|7z|vsd|vsdx|msg|one|pptx|ppt|avi|wav|docm|xltm|dotm|xlsm|p7s|sign|sig|sgn|pem|crt|cer|key|der|pkcs|pfx)$" />
----
====
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.
