= Настройки агрегации

include::user:page$grid-aggregate.adoc[tags=whatis]

Инструкцию по установке, настройке и требования к системе для установки {es} см. в документации модуля {pl}: xref:6.1@platform:console:search-elastic.adoc[Установка], xref:6.1@platform:console:search-elastic-configure.adoc[Настройка], xref:6.1@platform:ROOT:requirements-hardware.adoc#elastic[Требования].

[#availability]
== Доступность агрегации

Для работы с агрегацией требуется иметь опцию _Docsvision Модуль Интеллектуальный поиск_ лицензии {dv}. Если опция отключена, {es} работает как полнотекстовый поиск без функции агрегации.

.Агрегация доступна только для пользователей в следующих группах в конфигурационном файле модуля {pl} или в аналогичных группах Справочника сотрудников:
* _Использование агрегатов_ (*DocsVision Aggregation Users*).
* _{dv-admins-dir}_ (*{dv-admins-serv}*).
* _Продвинутые пользователи_ (*{dv-power-users-serv}*).
* _{dv-sec-admins-dir}_ (*{dv-sec-admins-serv}*).

Сотрудники, включённые в эти группы, получают доступ к использованию агрегации с {es}. Для пользователей, которым не разрешена работа с агрегацией, не отображается дополнительная  область в интерфейсе {wc}а. При использовании {es} для таких пользователей будут выводиться только результаты поиска.

Настройки включения в группы применятся только в новой сессии пользователя. Чтобы настройки применились, необходимо повторно выполнить вход в {wc}.

[#setting]
== Изменить количество вариантов агрегата

По умолчанию количество выводимых вариантов в агрегате равно 100.

Чтобы изменить это значение, в таблицу БД *dvsys_settings* добавьте настройку `FullTextIndexing_AggResultCount`, максимально возможная настройка `65,536` (65536 вариантов).

[#delay]
== Задержка обновления агрегации

// tag::webconfig[]
Администратор может настроить задержку обновления списка карточек и доступных агрегатов при использовании {es}.

.Чтобы настроить автоматическое применение по таймеру:
. Откройте файл `{webconfig}`.
. В секции {cnf-sgrps-wc}] измените значение параметра `Grid`:
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "Grid": {
          "ApplyAggregatesTimeout": "1000", <.>
          "ApplyAggregatesButton": "True" <.>
        }
      }
    }
  }
----
<.> По истечении указанного количества миллисекунд будет автоматически обновлён список карточек и доступные агрегаты.
<.> Флаг определяет, будет ли список карточек обновляться автоматически или перестраиваться по нажатию кнопки *Применить*. +
Доступные агрегаты обновляются согласно настройке `ApplyAggregatesTimeout`.
// end::webconfig[]
