= Отключить кэширование разметок фильтров данных

По умолчанию {wc} использует серверный кэш для хранения разметок фильтров данных в представлении. Кэш обновляется при перезапуске сервера {wc}, а также автоматически при изменении настроек представления.

Администратору нужно отключить кэширование разметок фильтров, если в {wc}е планируется использовать две или более разметки представлений. Если кэширование не отключено, пользователи могут получать разметки фильтра, не соответствующие условиям выбора разметок, указанным в программе {kvr}.

// tag::webconfig[]
.Чтобы отключить кэширование разметок:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {cnf-sgrps-wc}].
. Измените значение параметра `GridFilterCache` в `false`:
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "GridFilterCache": "False" <.>
        }
      }
    }
  }
----
<.> Возможные значения:
+
* `False` -- кэширование разметок фильтров будет отключено.
* `True` -- значение по умолчанию, кэширование включено.
// end::webconfig[]
+
include::partial$excerpts.adoc[tags=ifabsent]
+
. Сохраните изменения конфигурационного файла.
