= Режим скрытия правой боковой панели

На правой боковой панели отображаются параметры отправки документа на согласование, на ознакомление и пр. По умолчанию панель скрывается при нажатии на ней кнопок выполнения: *ОК*, *Отмена* и пр. Администратор может включить режим, при котором панель также будет скрываться по щелчку в любой области страницы {wc}а вне боковой панели.

include::partial$excerpts.adoc[tags=ifabsent]

// tag::webconfig[]
.Чтобы изменить режим скрытия панели:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {cnf-sgrps-wc}].
. Измените значение параметра `HideSidebarOnPageClick`:
+
Пример включения режима, при котором панель будет скрываться нажатием кнопки *ОК*/*Отмена* и пр., а также при щелчке вне боковой панели:
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "HideSidebarOnPageClick": "True" <.>
        }
      }
    }
  }
----
<.> Возможные значения:
+
* `False` (значение по умолчанию) -- панель должна скрываться только при нажатии кнопки *ОК*/*Отмена* и пр.
* `True` -- панель также должна скрываться при щелчке вне боковой панели.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.
