= Конфигурация модуля {wc}

Все настройки модуля хранятся в конфигурационном файле модуля `appsettings.json`. Конфигурационный файл может быть изменён в любом текстовом редакторе, например `nano`.

[source,bash]
----
sudo nano /usr/lib/docsvision/webclient/appsettings.json
----

.appsettings.json
[source,json]
----
{
  "Docsvision": {
    "WebClient": {
      "Authentication": {
        "DefaultDomain": "DOMAIN.COM" <.>
      },
      "Server": {
        "SessionManagerConnection": {
          "ConnectionAddress": "http://dvserver.domain.com:5000"  <.>
        }
      }
    }
  },
  "Ldap": {
    "AuthType": "Basic", <.>
    "Credential": {
      "UserName": "account@domain.com", <.>
      "Password": "password" <.>
    }
  },
  "SystemUserAccount": "account@domain.com", <.>
  "SystemUserPassword": "password", <.>
  "APIKEY": "anything" <.>
}
----
<.> Домен по умолчанию.
<.> Адрес сервера {dv}.
<.> Тип аутентификации: `Basic` -- аутентификация через LDAP, `Oauth` -- аутентификация через ЕСИА или Azure.
<.> Логин пользователя модуля.
<.> Пароль учётной записи пользователя.
<.> Имя системной учётной записи {dv}
<.> Пароль системной учётной записи в открытом или зашифрованном виде. Подробнее про шифрование см. в документации по установке системы, раздел "xref:install-linux::account-protection.adoc[]".
<.> Используется для аутентификации в API {wf}. При запуске бизнес-процесса из клиента через серверное расширение вызывается API сервера {wf}, который запускает данный БП.

[#launch]
== Запуск службы

[source,bash]
----
sudo systemctl start dvwebclient
----
