:root-cert: корневой сертификат удостоверяющего центраfootnote:[Например, корневой сертификат КриптоПро]

= Настройка компонентов КриптоПро

Для формирования усиленной подписи (с использованием сертификатов ЭП) необходимо установить компоненты КриптоПро и сертификаты.

Формирование усиленной подписи возможно только на персональных компьютерах, соответствующих требованиям:

* Операционная система: Windows, Mac OS или Linux (версии см. в https://www.cryptopro.ru/products/csp/compare[требованиях] КриптоПро CSP).
* Веб-браузер: Google Chrome, Яндекс.Браузер или Microsoft Edge на Chromium (поддерживаемые версии приведены в xref:ROOT:requirements-software.adoc#browser[требованиях к модулю]).

//

. Установите и активируйте расширение для браузера в зависимости от вашей операционной системы и используемого браузера:
+
* https://docs.cryptopro.ru/cades/plugin/plugin-installation-windows[Windows]
* https://docs.cryptopro.ru/cades/plugin/plugin-installation-unix[Linux]
* https://docs.cryptopro.ru/cades/plugin/plugin-installation-macos[MacOS]
+
. Установите сертификат пользователя.
+
* Установите *неквалифицированный* сертификат в хранилище "Личное" на уровне "Текущий пользователь".
* Установите *квалифицированный* сертификат на компьютер https://www.cryptopro.ru/products/csp/downloads[СКЗИ КриптоПро CSP] в хранилище _Личное_ на уровне _Текущий пользователь_.
. Установите
ifdef::root-cert[{root-cert}]
в хранилище _Доверенные корневые центры сертификации_ на уровне _Локальный компьютер_.

[#cloud]
== Настройка использования облачной подписи

// tag::webconfig[]
[WARNING]
====
Запросы к облачному сервису электронной подписи отправляются через сервер {wc}а. Это означает, что {wc} должен иметь доступ к сервису ЭП для отправки запросов на проверку подписи и для авторизации.
====

Проверка подлинности подписи может осуществляться локально или через облачный сервис электронной подписи. Способ проверки подписи зависит от настроек в файле конфигурации {wc}а.

.Чтобы изменить способ проверки подлинности подписи:
. Откройте файл конфигурации {wc}а по адресу `{webconfig}`.
. Перейдите к параметру `{cnf-sgrps}` и выполните следующие настройки:
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "CloudSignature": {
          "Address": "https://адрес-облачного-сервиса-DSS" <.>
          "ClientId": null <.>
          "SignServerAppName": null <.>
          "STSAppName": null <.>
          "DocumentStoreAppName": null <.>
          "VerifyUrl": "https://dss.cryptopro.ru/verify/rest/api/signatures" <.>
          "TSPServiceAddress": null <.>
          "SignatureType": "BES" <.>
          "AuthorizeRedirectUrl": "http://адрес-Web-клиента-Docsvision/api/CryptoProDss/AcceptAuthorization" <.>
          "TokenStorageMode": "InMemory" <.>
        }
      }
    }
  }
----
<.> Адрес сервиса облачной подписи.
<.> Идентификатор клиента. Настраивается в сервисе облачной подписи КриптоПро.
<.> Сервис подписи, обрабатывающий создание транзакций и получение результатов, подтвержденной операции.
<.> Сервис аутентификации, ответственный за аутентификацию пользователей для возможности обращений к сервису подписи и подтверждение транзакций.
<.> `SignServerAppName`, `STSAppName` и `DocumentStoreAppName` -- имена сайтов на сервере КриптоПро DSS. Настраиваются при установке сервиса электронной подписи КриптоПро DSS.
<.> URL для проверки подлинности подписи.
<.> Адрес сервиса штампа времени для XLT1.
<.> Тип подписи:
+
* `BES` -- будет использоваться CAdES-BES.
* `XLT1` -- будет использоваться CAdES-XLT1.
* `T` -- будет использоваться CAdES-T.
+
<.> URL, на который будет переадресован пользователь после авторизации в сервисе электронной подписи. Настраивается в сервисе электронной подписи.
<.> Режим хранения токена авторизации.
+
.Возможные значения:
* `Disabled` -- авторизация будет запрашиваться каждый раз.
* `InSessionCache` -- авторизация будет повторно запрошена по окончании сессии.
* `InMemory` -- авторизация будет запрошена при перезапуске *{wcs}*.
* `InUserProfileEncrypted` -- авторизация будет запрошена по истечении срока действия токена.
// end::webconfig[]

include::partial$excerpts.adoc[tags=ifabsent]

[#check-cloud]
== Проверка облачной подписи

Для проверки подлинности подписи при использовании xref:user:docs-sign-cloud.adoc[облачных сертификатов] необходимо выполнить дополнительную настройку.

. Запросите корневой сертификат КриптоПро для облачного сертификата.
. Установите корневой сертификат на сервере {wc}а.
. Убедитесь, что на сервере {wc}а установлены компоненты КриптоПро CSP версии {csp-v}.
. При необходимости установите также xref:6.1@backoffice:admin:prepare-cryptopro.adoc[компоненты] TSPCOM и OSPCOM. Получать лицензию на компоненты необязательно, для проверки подписи КриптоПро лицензия не требуется.
.. Выполните соответствующие xref:6.1@backoffice:admin:system-settings.adoc#signature-cypher[настройки] TSP и OCSP.
. После выполнения настроек станет доступна проверка подписей с использованием облачных сертификатов.
