= Установка и конфигурация серверного расширения

Серверное расширение {wc} должно быть установлено на компьютер с _сервером {dv}_ до установки (настройки) модуля _{wc}_.

[#linux]
== Установка на Linux

. Обновите индекс пакетов и установите сервер {wc}а командами:
+
[source,bash]
----
sudo apt-get update
sudo apt-get install docsvision-webclient
----

Пользователь, выполняющий настройку {dv}, должен являться локальным администратором (быть указанным в файле sudoers).

[WARNING]
====
Данная версия {wc}а не поддерживает работу с модулем _{am}_ версии 5.5.1.
// Если в {wc}е планируется работать с xref:user:directories/nomenclature/.directory.adoc[функциями] модуля _{am}_, установите серверную часть модуля _{am}_ на компьютер с сервером {dv} *перед* установкой серверного расширения {wc}а.
//
// Если {wc} уже установлен и планируется дополнительно установить модуль _{am}_ выполните следующие действия:
//
// . Установите сначала модуль _{am}_.
// . Затем xref:update-module.adoc[обновите {wc}] с установкой компонентов управления архивом.
====

[#config]
== Конфигурация модуля {wc}

Все настройки модуля хранятся в конфигурационном файле модуля `appsettings.json`. Конфигурационный файл может быть изменён в любом текстовом редакторе, например `nano`.

[source,bash]
----
sudo nano /usr/lib/docsvision/webclient/appsettings.json
----

.Фрагмент конфигурационного файла `appsettings.json`:
[source,json]
----
{
  "Docsvision": {
    "WebClient": {
      "Authentication": {
        "DefaultDomain": "DOMAIN.COM" <.>
      },
      "Server": {
        "SessionManagerConnection": {
          "ConnectionAddress": "http://dvserver.domain.com:5000"  <.>
        }
      }
    }
  },
  " Ldap": { <.>
    "AuthType": "Basic", <.>
    "Credential": {
      "UserName": "account@domain.com", <.>
      "Password": "password" <.>
    }
  },
  "DataProtectCertificateThumbprint": "thumbprint", <.>
  "SystemUserAccount": "account@domain.com", <.>
  "SystemUserPassword": "password", <.>
  "APIKEY": "api-key" <.>
}
----
<.> `DefaultDomain` -- домен по умолчанию.
<.> `ConnectionAddress` -- адрес сервера {dv}.
<.> `Ldap` -- имя и пароль учётной записи, под которой процесс обращается к ActiveDirectory.
<.> `AuthType` -- тип аутентификации: `Basic` -- аутентификация через LDAP, `Oauth` -- аутентификация через ЕСИА или Azure.
<.> `UserName` -- логин пользователя модуля для аутентификации LDAP.
<.> `Password` -- пароль учётной записи пользователя для аутентификации LDAP.
<.> `DataProtectCertificateThumbprint` -- отпечаток закрытого ключа шифрования SHA1. +
Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:6.1@install-linux::account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно удалить.
<.> `SystemUserAccount` -- имя системной учётной записи {dv}
<.> `SystemUserPassword` -- пароль системной учётной записи рекомендуется хранить в зашифрованном виде. Подробнее про шифрование см. в документации по установке системы, раздел "xref:install-linux::account-protection.adoc[]".
<.> `APIKEY` -- используется для подключения серверного расширения {wf}. Можно оставить значение по умолчанию или изменить, главное условие, чтобы значения в конфигурации модулей {wc}, {pl} и {wf} были одинаковые.

[#launch]
== Запуск службы

[source,bash]
----
sudo systemctl start dvwebclient
----
