= Настройка журналирования

События {wc}а протоколируются с помощью компонента NLog (http://nlog-project.org).

include::partial$nlog.adoc[]

// tag::webconfig[]
Базовые настройки журналирования представлены в панели управления (xref:control-panel-webc.adoc[Раздел "WebClient"]). Расширенные настройки осуществляются в конфигурационном файле {wc}а.

. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции menu:configuration[nlog].
. Измените параметры журналирования.
+
Измените значение атрибута *_fileName_* элемента menu:targets[target > target], чтобы настроить путь для сохранения журнала работы.
+
NOTE: В *_fileName_* можно использовать допустимые для Nlog переменные (https://github.com/nlog/NLog/wiki/File-target), например: `C:\Logs\$\{level}\WebClient_$\{shortdate}.log`.
+
Измените значение атрибута *_level_* элемента menu:rules[logger], например, на *_trace_*, чтобы включить протоколирование всех типов событий.
+
NOTE: Допустимые уровни протоколирования приведены на странице https://github.com/nlog/NLog/wiki/Configuration-file#log-levels.
+
Для получения дополнительной информации о других настройках NLog обратитесь к документации по данной платформе.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.
+
[NOTE]
====
Уровень журналирования может быть изменён методом `/api/Log/SetLogLevel`, если пользователь, который вызывает метод, состоит в группе *{dv-admins-serv}*. Методом можно задать следующие уровни: *_Trace = 0_*, *_Debug = 1_*, *_Info = 2_*, *_Warn = 3_*, *_Error = 4_* (любое другое значение будет распознано как *_Error_*).

// Данный способ применим для случая, когда есть потребность не перезагружать пул {wc}а.
После рестарта IIS уровень журналирования будет возвращён в исходное состояние в соответствии с конфигурационным файлом.
====

[#advanced-logging]
== Расширенное журналирование

{wc} поддерживает расширенное журналирование параметров производительности. Сюда входит точное логирование времени выполнения запросов {wc}а, время выполнения запросов к *{sss}* с привязкой к запросу {wc}а.

Для настройки доступно три фильтра журнала: По пользователю, По конкретному адресу, По времени запроса.

После включения диагностического логирования можно делать запросы. Если в параметре будет слеш (`\` или `/`), его необходимо переводить в URL код. Иными словами, заменять `example\usr01` на ``example%5Cusr0``1. Для отдельного запроса {wc}а можно посмотреть, какие запросы к *{sss}* выполнялись, время, потраченное на выполнение каждого из них, время, проведённое запросами на стороне *{sss}* и на стороне {wc}а, а также параметры запросов.

.Эта информация позволяет:
* Устанавливать причины аномально быстрого или медленного выполнения запроса {wc}а.
* Выявлять ошибки и неоптимальные места в работе {wc}а и Object Manager.
* Обнаруживать блокировки {wc}а и Object Manager.
* Выявлять проблемные запросы на сервере.

Чтобы включить диагностическое логирование, нужно в конфигурационном файле {wc}а для параметра `EnableDiagnosticsLogger` в разделе {setgroups-sys} указать значение `1`:

 <Setting Name="EnableDiagnosticsLogger" Value="1" />

Настроить параметры журналирования можно в конфигурационном файле следующим образом:

[source,xml]
----
<target name="DiagnosticsLogWebClient" xsi:type="AsyncWrapper">
  <target name="DiagnosticsLogFile" xsi:type="File" encoding="UTF-8" fileName="${basedir}/../Logs/DiagnosticLogWebClient${event-properties:item=Tenant} PID ${processId} ${shortdate}.tsv" layout="${message}" /> <.>
</target>
<target name="DiagnosticsLogStorageServer" xsi:type="AsyncWrapper">
  <target name="DiagnosticsLogSSFile" xsi:type="File" encoding="UTF-8" fileName="${basedir}/../Logs/DiagnosticLogStorageServer${event-properties:item=Tenant} PID ${processId} ${shortdate}.tsv" layout="${message}" /> <.>
</target>
----
<.> Адрес хранения журнала {wc}а. В параметре target важно добавить в имя файла `$\{processId}, например WebCDiagnostics PID$\{processId}.log`, а также указать `layout="$\{message}"`.
<.> Адрес хранения журнала *{sss}*. В параметре target важно добавить в имя файла `$\{processId}`, например `WebCDiagnostics PID$\{processId}.log`, а также указать `layout="$\{message}"`.

Журнал ведётся в формате `.tsv` и в дальнейшем может быть проанализирован через приложение для работы с журналами, например Log Parser Studio. Расширенный журнал по умолчанию сохраняется в стандартный каталог журналов {wc}а, но при помощи параметров конфигурации NLog можно записать в иной каталог.

Чтобы включить ведение расширенного журнала с требуемым фильтром, нужно выполнить в браузере запрос. Примеры запросов приведены далее.

[#query-sample]
=== Примеры запросов

. Запрос включения журнала для всех пользователей:
+
[subs=attributes]
 http://адрес-сервера-{wc}а/{dv}WebClient/api/DiagnosticsLog/AddLogUser?user=*
+
Журналируются все запросы `example\usr01`:
+
[subs=attributes]
 http://адрес-сервера-{wc}а/{dv}WebClient/api/DiagnosticsLog/AddLogUser?user=example%5Cusr01
+
. Запрос включения журнала по адресу:
+
[subs=attributes]
 http://адрес-сервера-{wc}а/{dv}WebClient/api/DiagnosticsLog/AddLogAddress?address=Grid%2FGetGridDataEx
+
Журналируются все запросы, в имени которых содержится подстрока `Grid/GetGridDataEx`. При необходимости можно журналировать все запросы конкретного контроллера:
+
[subs=attributes]
 http://адрес-сервера-{wc}а/{dv}WebClient/api/DiagnosticsLog/AddLogAddress?address=Grid
 http://адрес-сервера-{wc}а/{dv}WebClient/api/DiagnosticsLog/AddLogAddress?address=*
+
. Запрос включения журнала по времени:
+
[subs=attributes]
 http://адрес-сервера-{wc}а/{dv}WebClient/api/DiagnosticsLog/AddLogRequestTime?milliseconds=500
+
. Фильтры можно комбинировать. Ниже приведён пример включения фильтра для пользователя `example\usr01`, адреса `Grid/GetGridDataEx`, времени выполнения запросов `50` мс:
+
[subs=attributes]
 http://адрес-сервера-{wc}а/{dv}WebClient/api/DiagnosticsLog/AddLogUser?user=example%5Cusr01
 http://адрес-сервера-{wc}а/{dv}WebClient/api/DiagnosticsLog/AddLogAddress?address=Grid%2FGetGridDataEx
 http://адрес-сервера-{wc}а/{dv}WebClient/api/DiagnosticsLog/AddLogRequestTime?milliseconds=50
+
. Чтобы отключить ведение расширенного журнала, нужно выполнить запрос в браузере:
+
[subs=attributes]
 http://адрес-сервера-{wc}а/{dv}WebClient/api/DiagnosticsLog/Reset
