= Настройка журналирования

События {wc}а протоколируются с помощью компонента NLog (http://nlog-project.org).

include::partial$nlog.adoc[]

include::partial$excerpts.adoc[tags=ifabsent]

// tag::webconfig[]
// Базовые настройки журналирования представлены в панели управления (xref:..control-panel-webc.adoc[Раздел "WebClient"]).
Расширенные настройки журналирования осуществляются в конфигурационном файле {wc}а.

. Откройте конфигурационный файл `{webconfig}`.
. Измените параметры журналирования в параметре: menu:NLog[targets > target > target].
+
[source,json]
----
  "NLog": {
    "targets": {
        "async": true,
        "logFile": {
            "type": "File",
            "fileName": "${basedir}\\..\\Logs\\WebLayoutsDesigner${event-properties:item=Tenant} PID ${processId} ${shortdate}.log", <.>
            "layout": "[${longdate}][${level}][${callsite}] ${message} ${onexception:${newline}${exception:maxInnerExceptionLevel=10:format=shortType,message,stacktrace:separator=*:innerExceptionSeparator=&#xD;&#xA;&#x9;}}"
        }
    },
    "rules": [ <.>
        {
            "logger": "Microsoft.*",
            "minLevel": "Trace",
            "maxLevel": "Info",
            "final": true
            "writeTo": "logconsole" <.>
        },
        {
            "logger": "*",
            "minLevel": "Error",
            "writeTo": "logFile" <.>
        }
    ]
}
----
<.> Измените значение параметра `fileName`, чтобы настроить путь для сохранения журнала работы: +
В `fileName` можно использовать https://github.com/nlog/NLog/wiki/File-target[допустимые для NLog переменные], например: `\Logs\$\{level}\WebClient_$\{shortdate}.log`.
+
<.> Измените значение параметров `minLevel` и `maxLevel`, например, на `trace`, чтобы включить протоколирование всех типов событий. +
Допустимые уровни протоколирования приведены https://github.com/nlog/NLog/wiki/Configuration-file#log-levels[на странице NLog в GitHub]. +
Для получения дополнительной информации о других настройках NLog обратитесь к документации по данной платформе.
<.> Настройки журнала программы {pu}.
<.> Настройки журнала {wc}а.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.
+
[NOTE]
====
Уровень журналирования может быть изменён методом `/api/Log/SetLogLevel`, если пользователь, который вызывает метод, состоит в группе *{dv-admins-serv}*. Методом можно задать следующие уровни: *_Trace = 0_*, *_Debug = 1_*, *_Info = 2_*, *_Warn = 3_*, *_Error = 4_* (любое другое значение будет распознано как *_Error_*).

// Данный способ применим для случая, когда есть потребность не перезагружать пул {wc}а.
После перезапуска *{wcs-new}* уровень журналирования будет возвращён в исходное состояние в соответствии с конфигурационным файлом.
====
