= Настройка журналирования

События {wc}а протоколируются с помощью компонента NLog (http://nlog-project.org).

include::partial$nlog.adoc[]

include::partial$excerpts.adoc[tags=ifabsent]

// tag::webconfig[]
// Базовые настройки журналирования представлены в панели управления (xref:.control-panel-webc.adoc[Раздел "WebClient"]).
Расширенные настройки журналирования осуществляются в конфигурационном файле {wc}а.

. Откройте конфигурационный файл `{webconfig}`.
. Измените параметры журналирования в параметре: menu:NLog[targets > target > target].
+
[source,json]
----
  "NLog": {
    "targets": [
      {
        "target": {
          "name": "DefaultLogFileAsync",
          "xsi:type": "AsyncWrapper",
          "target": {
            "name": "DefaultLogFile",
            "xsi:type": "File",
            "encoding": "UTF-8",
            "archiveOldFileOnStartup": "true",
            "fileName": "${basedir}/../Logs/WebClient${event-properties:item=Tenant} PID ${processId} ${shortdate}.log", <.>
            "layout": "[${longdate}][${level}][${callsite}] ${action-info} ${message} ${exception:format=tostring,Data}" <.>
          }
        }
      }
    ]
  }
----
<.> Измените значение параметра `fileName`, чтобы настроить путь для сохранения журнала работы: +
В `fileName` можно использовать https://github.com/nlog/NLog/wiki/File-target[допустимые для NLog переменные], например: `\Logs\$\{level}\WebClient_$\{shortdate}.log`.
+
<.> Измените значение атрибута `level` элемента menu:rules[logger], например, на `trace`, чтобы включить протоколирование всех типов событий. +
Допустимые уровни протоколирования приведены https://github.com/nlog/NLog/wiki/Configuration-file#log-levels[на странице NLog в GitHub]. +
Для получения дополнительной информации о других настройках NLog обратитесь к документации по данной платформе.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.
+
[NOTE]
====
Уровень журналирования может быть изменён методом `/api/Log/SetLogLevel`, если пользователь, который вызывает метод, состоит в группе *{dv-admins-serv}*. Методом можно задать следующие уровни: *_Trace = 0_*, *_Debug = 1_*, *_Info = 2_*, *_Warn = 3_*, *_Error = 4_* (любое другое значение будет распознано как *_Error_*).

Данный способ применим для случая, когда есть потребность не перезагружать пул {wc}а. После рестарта IIS уровень журналирования будет возвращён в исходное состояние в соответствии с конфигурационным файлом.
====
