= Протоколирование событий

. При остановке сервиса _{wcs-new}_ в файл журнала {wc}а добавляется запись о завершении {wc}а, например:
+
 [2022-10-26 17:38:08.1840][Error][DocsVision.Platform.WebClient.Diagnostics.Trace.TraceError]  Application end: HostingEnvironment
+
. При старте сервиса _{wcs-new}_ создаётся новый файл журнала {wc}а.
. К названию файла журнала добавляется ID процесса и дата запуска {wc}а: 
+
 WebClient${event-properties:item=Tenant} PID $\{processId} $\{shortdate}.log
+
Например: `WebClient PID 4592 2022-10-26.log`
+
. В созданный файл добавляется сообщение о старте {wc}а, например:
+
 [2022-10-26 17:11:56.8774][Error][DocsVision.Platform.WebClient.Diagnostics.Trace.TraceError]  Application start

[#requests]
== Протоколирование запросов

Протоколирование запросов полезно для анализа входящих запросов и ответов на них, заголовков и т.д.

.Журнал запросов содержит следующую информацию:
* HTTP запросы и ответы.
* Дата и время запросов и ответов.
* Заголовки

Протоколирование запросов настраивается в конфигурационном файле модуля по адресу `{webconfig}`, за настройку отвечает параметр `W3CLogging`:

[source,json]
----
"W3CLogging": {
	"IsEnabled": false <.>
	"LogDirectory": "/var/log/docsvision/webclient/", <.>
	"LoggingFields": "Date,Time,ServerName,Method,UriStem,UriQuery,ProtocolStatus,TimeTaken,ProtocolVersion,Host,UserAgent,Referer,ConnectionInfoFields", <.>
	"FileSizeLimit": 10485760, <.>
	"RetainedFileCountLimit": 4, <.>
	"FileName": "webclient-w3c.log" <.>
}
----
<.> Включение/отключение протоколирования событий.
<.> Путь к журналу.
<.> Журналируемые поля. По умолчанию указываются запросы, ответы, заголовки, дата/время и имя сервера.
<.> Максимальный размер файла журнала, после которого будет создаваться новый. Значение в байтах, по умолчания 10 Мб.
<.> Количество сохраняемых файлов журнала. Допустимые значения от 1 до 10000.
<.> Имя файла журнала.
