= Ограничить количество отображаемых карточек в папке

{wc} ограничивает количество карточек, отображаемых на одной странице представления папки. Ограничение устанавливается или для всех папок, или для каждой папки по отдельности. В первом случае используется параметр, который настраивается в конфигурационном файле {wc}. Во втором случае максимальное количество вычисляется из свойств папки, настроенных в {wincl}е.

[NOTE]
====
Ограничение распространяется только на представление папки -- результаты поиска по представлению, результаты полнотекстового поиска и т.п. настройкой не ограничены.
====

// tag::webconfig[]
По умолчанию {wc} использует собственное ограничение максимального количества в 15 карточек на страницу представления.

.Чтобы изменить максимальное количество карточек на страницу представления:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к элементу {cnf-sgrps} > View] и измените параметры `UseFolderPropertyRestrictionPageSize` и `DefaultPageSize` при необходимости.
+
[source,json]
----
  "Docsvision": {
    "SettingGroups": {
      "WebClient": {
        "View": {
          "UseFolderPropertyRestrictionPageSize": "true", <.>
          "DefaultPageSize": "20" <.>
        },
      },
    },
  },
----
<.> Параметр "Ограничение количества выводимых записей" отвечает за использование ограничений, установленных в свойствах папок:
* `true` -- использовать ограничение, установленное в {dv}.
* `false` -- использовать собственное ограничение {wc}, заданное параметром `DefaultPageSize` (значение по умолчанию).
<.> Параметр `DefaultPageSize` изменяет максимальное отображаемое количество карточек на страницу. Если в настройках папки ограничение не установлено, то в представлении папки будут отображаться все карточки без разбивки на страницы.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.

NOTE: Если параметр отсутствует в конфигурационном файле, создайте его.
