= Ограничить размер прикладываемых файлов

В {wc}е по умолчанию действует несколько ограничений, влияющих на возможность прикладывания "тяжелых" файлов:

* Максимальный размер файла, прикладываемого при создании карточки. Значение по умолчанию: 50 Мб.
* Максимальный размер всех прикладываемых файлов одной карточки. Значение по умолчанию: 128 Мб.

Администратор системы может изменить действующее ограничение.

// tag::webconfig[]
. Чтобы изменить ограничение для максимального размера единичного файла, в конфигурационном файле `{webconfig}` перейдите к параметру {cnf-wc} > View > MaxUploadFileItemSize"].
+
[source,json]
----
  "Docsvision": {
    "SettingGroups": {
      "WebClient": {
        "View": {
          "MaxUploadFileItemSize": "0" <.>
        },
      },
    },
  },
----
<.> Укажите новое ограничение для максимального размера единичного файла в байтах, не превышающее `2147483647`.
+

. Чтобы изменить ограничение для максимального общего размера всех добавляемых файлов карточки, перейдите к элементу menu:Kestrel[Limits].
+
[source,json]
----
  "Kestrel": {
    "Limits": {
      "MaxRequestBodySize": "0" <.>
    }
  }
----
<.> Укажите новое ограничение максимального общего размера всех добавляемых файлов карточки в байтах, не превышающее `4294967295`.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.
