= Ограничить размер прикладываемых файлов

В {wc}е по умолчанию действует несколько ограничений, влияющих на возможность прикладывания файлов большого размера:

* Максимальный размер файла, прикладываемого при создании карточки (параметр `MaxUploadFileItemSize`). Значение по умолчанию: 50 Мб.
// * Максимальный размер всех прикладываемых файлов одной карточки. Значение по умолчанию: 128 Мб.
* Максимальный размер тела запроса (параметр `MaxRequestBodySize`), по умолчанию приблизительно равен 28,6 Мб.

Администратор системы может изменить действующее ограничение путём редактирования файла `{webconfig}`. В случае отсутствия необходимых параметров конфигурации, создайте их самостоятельно.

// tag::webconfig[]
. Чтобы изменить ограничение для максимального размера единичного файла, в конфигурационном файле `{webconfig}` перейдите к параметру {cnf-wc} > View > MaxUploadFileItemSize"].
+
[source,json]
----
  "Docsvision": {
    "SettingGroups": {
      "WebClient": {
        "View": {
          "MaxUploadFileItemSize": "0" <.>
        },
      },
    },
  },
----
<.> Укажите новое ограничение для максимального размера единичного файла в байтах, не превышающее `2147483647`.
+
. Чтобы изменить ограничение для максимального размера тела запроса, перейдите к элементу menu:Kestrel[Limits]. Параметр может быть изменён, когда необходимо ограничить сетевой запрос.
+
[source,json]
----
  "Kestrel": {
    "Limits": {
      "MaxRequestBodySize": "0" <.>
    }
  }
----
<.> Укажите новое ограничение максимального размера тела запроса в байтах, не превышающее `4294967295`.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.
