= Настройка "Р7Офис. Сервер документов"

"Р7-Офис. Сервер документов" или "OnlyOffice" используется для предварительного просмотра файлов в карточках и для консолидации версий документов при согласовании. Данный раздел описывает установку и настройку Р7-Офис. Сервер документов, а также подготовку {wc}а для использования функций предварительного просмотра и консолидации.

Предварительный просмотр при помощи "Р7-Офис. Сервер документов" или OnlyOffice позволяет отображать предпросмотр не печатной версии документа, а непосредственно файла. Например, для документа Excel появляется возможность скопировать данные из файла с сохранением структуры и форматирования. Все прежние функции поддерживаются как в стандартной реализации.

.Чтобы активировать новый режим предварительного просмотра, выполните шаги следующей инструкции:
. Установите "Р7-Офис. Сервер документов" согласно официальной инструкции на https://support.r7-office.ru/document_server/install-document_server/document_server_linux/install_ds_astalinux_debian_ubuntu/[сайте Р7-Офис].
. Если все действия выполнены правильно, при открытии в браузере адреса `\http://localhost` появится сообщение "Сервер документов запущен".
+
****
При возникновении проблем с установкой PGSQL подключите репозиторий {pgsql}:

 echo "deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

И измените приоритет репозитория в строке `Pin-Priority` файла:

 sudo nano /etc/apt/preferences.d/pgdg.pref

Измените значение приоритета следующим образом: `Pin-Priority: 910` и выполните команду `sudo apt update`.
****
+
. [[consolidation]]Для включения консолидации через Р7-Офис в файл `ds-docservice.conf` добавьте локацию
+
[source]
----
location ~* ^(\/upload.)(\/.)$ {
  alias /tmp$1$2;
  add_header Content-Disposition "attachment; filename*=UTF-8''$arg_filename";
}
----
+
. Переведите сервер документов на использование HTTPS. Для этого на сервере с установленным Р7 необходимо установить самоподписанный сертификат.
+
Создать сертификат можно при помощи утилиты https://slproweb.com/products/Win32OpenSSL.html[OpenSSL].
. Запустите Win64 OpenSSL Command Prompt от имени администратора, перейдите в директорию, в которой располагается файл `r7-cert.pfx`
. Выполните команду:
+
[source,bash]
----
openssl req -x509 -newkey rsa:2048 -keyout test.key -nodes -out test.crt -subj "/CN=r7.domain.com <.>
----
<.> Вместо `r7.domain.com` укажите имя сервера с установленным Р7.
+
. Установите сертификат в системе, поместив его в папку `/usr/local/share/ca-certificates/`, после чего необходимо будет выполнить команду:
+
 sudo update-ca-certificates -v -f.
+
. После установки сертификата переключите Р7 на использование HTTPS с созданным сертификатом согласно https https://support.r7-office.ru/document_server/install-document_server/document_server_linux/https_ds/[официальной инструкции на сайте Р7].
. <<webc-config,Переведите>> {wc} на использование HTTPS.
// +
// [NOTE]
// ====
// Чтобы избежать ошибки с сертификатом на пользовательских машинах, потребуется либо локально установить сгенерированный сертификат, либо перейти на URL сервера документов, например, `\https://r7team.com:8083/` и там выбрать перейти на сайт.
// ====
. В файле `/etc/r7-office/documentserver/local.json` задайте для параметров `inbox`, `outbox` и `browser` значение `false`.

[#webc-config]
== Конфигурация {wc}а

Для использования "Р7-Офис. Сервер документов" требуется перевести {wc} на использование HTTPS.

. Создайте самоподписанный сертификат при помощи утилиты https://slproweb.com/products/Win32OpenSSL.html[OpenSSL]:
+
 openssl req -x509 -newkey rsa:4096 -sha256 -keyout .\out\cert.key -out .\out\certificate.crt -subj "/CN=http://WebClientDomain.com" -days 600
+
. Откройте конфигурационный файл {wc}а по адресу `{webconfig}` в любом текстовом редакторе и отредактируйте следующие параметры:
+
[source,json]
----
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "https://*:5004", <.>
        "Certificate": {
        "Path": "/path/to/your.crt", <.>
        "KeyPath": "/path/to/your.key" <.>
      }
    }
  }
----
<.> Адрес, по которому будет доступен {wc}.
<.> Путь к сертификату.
<.> Путь к закрытому ключу сертификата.
+
. Следующим шагом необходимо указать адрес сервера документов Р7 для предварительного просмотра и консолидации в конфигурационном, указать режим предварительного просмотра:
// tag::webconfig[]
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "ServerR7ConnectionAddress": "https://dvserver.preview.com", <.>
          "ServerR7UploadDirectory": "/tmp/upload", <.>
          "FilePreviewMode": "2", <.>
        }
      }
    }
  }
----
<.> `ServerR7ConnectionAddress` -- URL сервера документов Р7-Офис/OnlyOffice. Настройка обязательна для заполнения. Если URL сервера документов Р7 не указан, остальные настройки будет проигнорированы, и будет использоваться стандартный инструмент предварительного просмотра PDF.js.
<.> `ServerR7UploadDirectory` -- каталог загрузки консолидируемых файлов.
<.> `FilePreviewMode` -- определяет, какой компонент используется для предпросмотра. Значения: `0` -- предпросмотр отключен, `1` -- предпросмотр с использованием PDF.js, `2` -- предпросмотр с помощью Р7.
// end::webconfig[]
