= Настройки сканирования с помощью DVSupService

По умолчанию сканирование с помощью ЭУ "xref:layouts:ctrl/special/scanButton.adoc[]" работает только в ОС Windows с помощью программы DVWebtool, чтобы иметь возможность сканировать файлы в ОС Linux, необходимо выполнить дополнительные действия по настройке DVSupService для работы со сканерами с поддержкой SANE. Установка DVSupService описана в разделе "xref:user:prepare-add-components.adoc#dvSupService[Установка и запуск службы DVSupService]".

[#scan-provider]
== Выбор провайдера сканирования

В конфигурационном файле утилиты по адресу `/usr/lib/docsvision/dvsupservice/appsettings.json` параметр `ScanProviders` позволяет задать провайдеры сканирования:

[source,json]
----
"ScanProviders": [
    "Naps2Provider" <.>
  ],
----
<.> Провайдер сканирования. Возможные значения: `"Naps2Provider"`, `"ScanImageProvider"`.

Если подключено несколько провайдеров, рядом с именем сканера в интерфейсе сканирования карточки будет отображаться название провайдера, чтобы избежать дублирования пунктов.

[#sane]
== Настройка сканирования

На машине с Linux и подключенным сканером необходимо установить компоненты SANE, выполнив в командной строке:

[tabs]
====
Astra Linux::
+
 $ sudo apt install sane

РЕД ОС::
+
 $ sudo dnf install sane

====

Если планируется использовать только провайдер `Naps2Provider`, дополнительные компоненты устанавливать не требуется. Если планируется использовать провайдер `ScanImageProvider`, необходимо установить пакет `sane-utils` командой:

[tabs]
====
Astra Linux::
+
 $ sudo apt install sane sane-utils

РЕД ОС::
+
 $ sudo dnf install sane sane-utils
====
