= Установка минимального количества потоков

Иногда при работе {wc}а может наблюдаться снижение производительности даже при условии соблюдения всех системных требований. Это может выражаться в виде периодического замедления в начале рабочего дня или после рассылки писем со ссылкой на {wc}, в таких случаях замедление обычно продолжается не более 1-2 минут. Время отклика страницы может увеличиваться до минуты.

Причина такого поведения заключается в слишком долгой адаптации сервера {wc}а к повысившейся активности пользователей.

Решением ситуации является установка минимального числа потоков, которое соответствовало бы операционному состоянию сервера {wc}а. Значение устанавливается в переменной окружения `COMPlus_ThreadPool_ForceMinWorkerThreads` для пула {wc}а.

Минимальное число потоков определяется в соответствии с числом активных пользователей (максимальным числом активных-сессий). Более точное значение можно определить, проанализировав показатели xref:performance-counters.adoc[счетчика производительности] `ThreadPool Thread Count` в течение рабочего дня. Среднее значение счетчика под нагрузкой можно использовать как минимальное число потоков.

После того как вы задали или изменили переменную, необходимо перезапустить IIS.
