= Включить аутентификацию Kerberos

Чтобы иметь возможность использования сквозной аутентификации, когда сервер расположен в ОС Linux, необходимо выполнить специальные настройки Kerberos и используемого браузера.footnote:[Необходимые настройки можно получить через службу технической поддержки {dv}.]

.Обязательные условия для настройки сквозной аутентификации:
* Обращение к {wc}у по доменному имени и адресу `\http://example.domain.com:5004/Account/LoginWindows`.
* Сервер {wc}а должен находиться в домене.

//

. Настройте аутентификацию в Active Directory (требуется не для всех сервисов). Для работы Kerberos аутентификации в ActiveDirectory, необходимо получить keytab-файл.
+
--
include::6.1@mgmtconsole:admin:provide-access.adoc[tags=keytab]
--
+
. Перейдите по адресу {wc}а `\http://example.domain.com:5004/Account/LoginWindows`. Адрес необходимо вводить с доменным именем. При обращении по IP Kerberos-аутентификация в {wc}е использоваться не будет, будет использована только стандартная аутентификация.
+
NOTE: В настройках безопасности браузера сайт должен находиться в локальной интрасети.
