= Шаблоны для определения типа клиентского устройства

// tag::webconfig[]
Пользовательский интерфейс {wc}а адаптируется под тип клиентского устройства, который определяется по https://ru.wikipedia.org/wiki/User_Agent[User Agent], передаваемому веб-браузером клиента. Если User Agent не сопоставляется или некорректно сопоставляется с типом устройства, нужно изменить шаблон, по которому выполняется сопоставление:

. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к элементу {cnf-sgrps-wc}].
. Измените значение параметра `TabletRegExpString`:
+
.Определять устройство с User Agent "NEWPAD" как планшет
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "TabletRegExpString": "SM-T355|MediaPad|NEWPAD" <.>
        },
      },
    },
  },
----
<.> В значении параметра через символ `|` нужно указать User Agent соответствующего устройства.
+
* `MobileRegExpString` -- шаблон определения мобильных устройств нового поколения.
* `MobileRegExpPart2String` -- шаблон определения старых мобильных устройств.
* `TabletRegExpString` -- шаблон определения планшетов.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.

NOTE: Адаптивные свойства разметок могут быть xref:layouts:layouts-adaptive.adoc[настроены] в программе {kvr}.
