= Расширение возможностей программы {kvr}

{kvr} предоставляет возможность дополнять собственные функциональные возможности с помощью расширений.

Расширение программы {kvr} может добавлять:

* Типы элементов управления.
* Свойства (настройки) элементов управления.
* Редакторы для свойств элементов управления.
* Функции проверки доступности операций.
* Критерии для условий выбора разметок.
* Локализованные ресурсы.

== Перечень необходимых инструментов

include::ROOT:partial$excerpts.adoc[tags=wc-version]
include::ROOT:partial$excerpts.adoc[tags=vscode]
* Docsvision WebClient SDK (запрашивается через портал ТП).

== Описание файлов проекта

* В корне репозитория расположено решение для Visual Studio (`Samples.sln`) и ключ для подписания сборок примеров (`StrongNameKey.snk`).
* `Assemblies` -- сборки, необходимые для использования примеров
* `ServerExtension.cs` -- входная точка расширение, в которой регистрируются описания контролов и прочие сущности.
* `Sign.snk` -- файл подписи сборки. Для установки сборки должны быть подписаны. Рекомендуется сгенерировать новый файл подписи в настройках проекта.
* `Resource.resx`, `Resource.ru.resx` -- локализации, используемые в расширении.
* `Constants.cs` -- файл для объявления констант.

== Разработка расширения программы {kvr}

.Процесс разработки расширения программы {kvr} может включать следующие шаги:

. Создание в Visual Studiofootnote:[Рекомендуется использовать Visual Studio Code {vscode-v}.] проекта типа TemplateDesignerExtension.
+
. Обновление ссылок на подключаемые компоненты (при необходимости).
+
WARNING: Версии подключаемых компонентов в проекте должны соответствовать версиям компонентов, используемых Конструктором web-разметок, для которого разрабатывается расширение. При обновлении версии {wc}а все разработанные компоненты должны быть скомпилированы повторно с использованием новых версий библиотек {wc}а.
+
. Разработка ядра расширения программы {kvr}.
+
Ядро расширения программы {kvr} представляет собой производный от `WebLayoutsDesignerExtension` класс. В нём переопределяются методы получения описателей типов элементов управления, описателей типов свойств элементов управления, редакторов значений свойств и пр., в зависимости от назначения расширения программы {kvr}.
+
При создании проекта из шаблона `TemplateDesignerExtension` ядро расширения программы {kvr} будет содержаться в файле `Extension\TemplateDesignerExtension.cs`.
+
Примеры реализации отдельных элементов ядра расширения программы {kvr} рассмотрены в следующих разделах.
+
. Компиляция проекта.
+
****
В результате будет получен файл DLL -- расширение программы {kvr}, а также файлы DLL с локализованными ресурсами.
****

== Публикация расширения программы {kvr}

Последовательность публикации расширения программы {kvr} на сервере {wc}а включает следующие шаги:

. Компиляция проекта.
+
****
В результате будет получен файл DLL с ядром расширения программы {kvr} и реализуемыми функциями, а также файлы DLL с локализованными ресурсами.
****
+
. Создание каталога для Решения на сервере {wc}а: `Каталог-установки-Конструктора-Web-Разметок/Plugins/%Каталог Решения%`.
. Копирование сборки расширения программы {kvr} в `%Каталог Решения%`. Файлы DLL с локализованными ресурсами копируются в существующие в каталоге `/ru/` (для русской локализации), `/uk/` (для английской локализации) и т.д.
+
****
Реализованная в расширении программы {kvr} функциональность будет доступна после запуска программы {kvr}.
****
. Перезапуск {kvr}.
