= Изменения в релизной версии

[#functional]
== Функциональные изменения

[#old-grid]
Старый грид::
Старый грид был удалён и больше не может быть использован. Также удалена локация в программе {kvr}, использовавшаяся только для старого грида.

[#js]
Примеры на JavaScript::
Раздел "Особенности реализации скриптов на JavaScript" упразднён. Написание расширений на JavaScript не рекомендуется.

[#in-mask]
Маска ввода::
Для элемента управления `_Строка_` добавлено свойство "xref:layouts:ctrl/standard/textBox.adoc#input-mask[Маска ввода]", для написания регулярных выражений (regexp) для задания масок с использованием синтаксиса языка Perl.

[#task-control]
Ход исполнения переведён на React::
Реализация элемента управления, отображающего информацию о заданиях группы заданий, переведена на React. Для работы ЭУ в стандартных разметках изменений не требуется. Если элемент управления использовался в собственных разметках, его необходимо удалить и повторно добавить.

[#api]
== Изменения в API

* Устаревшим объявлен метод `validate`, использовавшийся в следующих ЭУ:
+
** Адрес
** Нумератор
** Партнер
** Подразделение контрагента
** Записи справочника сотрудников
** Дата/время
** Число
** Строка
** Строка конструктора справочников
** Текст
+
Вместо указанного метода рекомендуется использовать `validateAsync`.
+
* Добавлено отменяемое событие `validating`, при помощи которого можно создавать собственную проверку корректности заполнения.
// При подписке на это событие в скрипте в аргументах приходит объект с результатом проверки. Описав собственную валидацию и мутируя объект результата валидации из аргументов возможно вывести собственное сообщение об ошибке. Примеры
* Добавлен API параметр `tableRenderer` для переопределения отрисовки ЭУ `_Таблица исполнения_`. Параметр является объектом, в нём можно переопределить поля, каждое из которых позволяет переопределить отрисовку части таблицы.
* Оптимизирован API для работы с подписями файлов в модуле "{em}".
** В `$DigitalSiignature` добавлена возможность подписывать произвольный набор байт.
** Добавлен API для выбора сертификата (без подписи) и подписи с заранее выбранным сертификатом.
** На сервере добавлен API для проверки подписи, представленной набором байт.

// [#samples]
// == Новые примеры в репозитории на GitHub

[#controls]
== Изменения в библиотеке элементов управления

[#task-parent-group]
ЭУ "Родительская группа заданий"::
Элемент управления `_Родительская группа заданий_` удалён, техническая поддержка по нему больше не оказывается. Необходимо использовать ЭУ "xref:layouts:ctrl/standard/locationContainer.adoc[]".

[#optimizations]
== Оптимизации

// * [[GBL-3415]]Добавлено отслеживание ошибок и правил написания исходного кода, позволяющее предупредить возможные проблемы с работой модуля на стадии разработки.
* [[wc-edi]]Устранены дублирования кода расширения {wc}а, отвечающего за работу с Модулем интеграции с операторами ЭДО через web-интерфейс, в частности:
+
** Код, отвечающий за подписание входящих формализованных документов.
* [[GBL-2949]]Проведена проверка безопасности frontend-части {wc}а на уровне исходного кода, исправлены уязвимости, включая, но не ограничиваясь уязвимостями в элементах управления `_Ссылки_`, `_Комментарии_`, `_Таблица исполнения_`, `_Html тег_`, `_Метка_`, компонентах меню пользователя, модальных окон, компонентах элементов управления для работы с сотрудниками, диалоге выбора ссылки на карточку, результатах поиска, элементах дерева папок.
