= Изменения в релизной версии

[#functional]
== Функциональные изменения

[#dvsupservice]
Служба DVSupService::
Разработан аналог DvWebTool -- служба DVSupService для открытия файлов в офисном редакторе. Служба устанавливается только в ОС Linux и позволяет открывать офисные файлы в ассоциированном редакторе. Подробнее см. "xref:user:prepare-add-components.adoc#dvsupservice[Установка и запуск службы DVSupService]".

[#consolidation]
Консолидация с использованием Р7::
Стандартный механизм консолидации был заменён на серверную консолидацию через Р7-Офис. Вместо использования офисного приложения на клиентском компьютере для консолидации используется Р7-Офис, установленный на сервере. При объединении версий файлов в карточке открывается окно Р7-Офис. Подробная инструкция по настройке приведена в разделе "xref:admin:preview-r7.adoc[]".

[#preview]
Предпросмотр с использованием Р7::
Предварительный просмотр файлов в карточках теперь по умолчанию отключен. Чтобы включить предварительный просмотр, потребуется установить "Р7 Сервер документов" и настроить {wc} на использование HTTPS. Подробная инструкция по активации предварительного просмотра приведена в документации по администрированию модуля, раздел "xref:admin:preview-r7.adoc[]".

[#aggregate]
Количество вариантов в агрегате::
Количество выводимых вариантов агрегата увеличено до 100. Настройку по умолчанию можно изменить через БД, подробнее см. "xref:admin:grid-aggregate.adoc#setting[Изменить количество вариантов агрегата]".

[#req-sign]
ПО для формирования подписи::
Обновлены xref:ROOT:requirements-signature.adoc[требования] для формирования электронной подписи. В новой версии модуля для проверки и формирования простой и усиленной ЭП требуется CSP версии {csp-v}, также требуется Криптосервис обслуживания ЭП, см. подробнее в руководстве по настройке системы xref:6.1@engineer:ROOT:java-service.adoc[].

[#net6]
Переход на .NET 6  и установка Linux::
Новая версия модуля переведена на .NET 6.0 с возможностью установки на ОС Astra Linux.

[#update]
Изменён процесс обновления::
Процесс обновления серверного расширения {wc} изменён. Теперь при установке серверного расширения диалог с обновлением БД не появляется, требуется обновить БД через {cns}.

[#build-no]
Новый формат версии сборки::
Был обновлён формат версий сборки модуля, web-расширений и решений. В окне свойств инсталлятора и в окне "О программе" версия отображается в новом формате: `Мажорная.Минорная.Сборка+Хэш-коммита`, например: `6.1.1234+fbf13f3159`. В программе {kvr} версия решений отображается в виде `Мажорная.Минорная`, например, `6.1`.

[#versioning]
Обновление версии модуля::
Версии управляемых компонентов {dv} (.NET) были изменены с 5.5 на 6.0. Версии неуправляемых компонентов {dv} (С++, VB 6.0) не изменились.

[#cades-t]
Формирование подписи CAdES-T::
Подпись типа CAdES-T больше не может быть сформирована в {dv}. Проверка подписи типа CAdES-T остаётся неизменной, как и формирование подписей типов CAdES-X Long Type 1 и CAdES-BES.

// .Изменения МЧД
// [%collapsible]
// ====
// [#ogrn]
// Поле ОГРН для организаций::
// Для организаций в справочнике сотрудников и справочнике контрагентов добавлено новое поле _ОГРН (ОГРНИП)_.
//
// [#attorney]
// Справочник полномочий для доверенностей::
// Разработан справочник для работы с МЧД, подробнее см. "xref:user:directories/powers/.directory.adoc[]".
//
// [#field]
// Новое поле в справочнике сотрудников::
// В карточку сотрудника, на вкладку _Основная_ добавлен флаг `*Требуется доверенность при подписании документов*`. Флаг влияет на алгоритм выбора МЧД при подписании документа и учитывается при проверке необходимости использования МЧД для сотрудника. См. подробнее в xref:user:directories/staff/employee-fields.adoc#attorney[пользовательской документации].
//
// Новый элемент управления::
// Для выбора полномочий из справочника добавлен ЭУ "xref:layouts:ctrl/directories/.powers.adoc[]".
// ====

// [#api]
// == Изменения в API
//
//
//
// [#samples]
// == Новые примеры в репозитории на GitHub


