= Изменения в релизной версии

[#functional]
== Функциональные изменения

[#net6]
Переход на .NET 6  и установка Linux::
Новая версия модуля переведена на .NET 6.0 с возможностью установки на ОС Astra Linux.

[#update]
Изменён процесс обновления::
Процесс обновления серверного расширения {wc} изменён. Теперь при установке серверного расширения диалог с обновлением БД не появляется, требуется обновить БД через {cns}.

[#build-no]
Новый формат версии сборки::
Был обновлён формат версий сборки модуля, web-расширений и решений. В окне свойств инсталлятора и в окне "О программе" версия отображается в новом формате: `Мажорная.Минорная.Сборка+Хэш-коммита`, например: `6.1.1234+fbf13f3159`. В программе {kvr} версия решений отображается в виде `Мажорная.Минорная`, например, `6.1`.

Обновление версии модуля::
Версии управляемых компонентов {dv} (.NET) были изменены с 5.5 на 6.0. Версии неуправляемых компонентов {dv} (С++, VB 6.0) не изменились.

// .Изменения МЧД
// [%collapsible]
// ====
// [#ogrn]
// Поле ОГРН для организаций::
// Для организаций в справочнике сотрудников и справочнике контрагентов добавлено новое поле _ОГРН (ОГРНИП)_.
//
// [#attorney]
// Справочник полномочий для доверенностей::
// Разработан справочник для работы с МЧД, подробнее см. "xref:user:directories/powers/directory.adoc[]".
//
// [#field]
// Новое поле в справочнике сотрудников::
// В карточку сотрудника, на вкладку _Основная_ добавлен флаг `*Требуется доверенность при подписании документов*`. Флаг влияет на алгоритм выбора МЧД при подписании документа и учитывается при проверке необходимости использования МЧД для сотрудника. См. подробнее в xref:user:directories/staff/employee-fields.adoc#attorney[пользовательской документации].
//
// Новый элемент управления::
// Для выбора полномочий из справочника добавлен ЭУ "xref:layouts:ctrl/directories/powers.adoc[]".
// ====

// [#api]
// == Изменения в API
//
//
//
// [#samples]
// == Новые примеры в репозитории на GitHub


