= Панель отправки на ознакомление

Данный раздел содержит описание примера с элементом управления `_Панель отправки на ознакомление_`, который демонстрирует запуск бизнес-процесса из карточки документа и создание собственной боковой панели.

include::ROOT:partial$excerpts.adoc[tags=wc-node]
include::ROOT:partial$excerpts.adoc[tags=vscode]

== Проект "AcquaintancePanelDesignerExtension"

. Проект-расширение для конструктора разметок. Содержит описание элемента управления `_Пример боковой панели_` для программы {kvr}.
. Демонстрирует использование описания ЭУ в формате `.xml`, задание ему стандартных свойств, реализованных в программе {kvr} и добавление собственного свойства, используя класс `PropretyDescription`.

== Проект "AcquaintancePanelServerExtension"

* Проект-расширение для {wc}. Содержит бизнес-логику и реализацию элемента управления на клиенте.
* Демонстрирует расширение функционала с помощью добавления новых сервисов, моделей, контроллеров.
* Реализован контроллер `LayoutBusinessProcessController` с методом `SendToAcquaintance`, который вызывает сервис `ILayoutBPService` для отправки документа на ознакомление. В контроллере принудительно записан идентификатор бизнес-процесса.
* Для старта этого бизнес-процесса необходимо передать в качестве параметров "Ознакомителей" (`Performers`), "Документ" (`Document`) и дату "Ознакомиться до" (`EndDate`).

== Проект "AcquaintancePanelWebExtension"

* Клиентский ЭУ представляет собой кнопку, при нажатии на которую появляется боковая панель.
* Боковая панель включает в себя стандартные ЭУ {wc}:
** `_Сотрудники_` для задания списка сотрудников, которым придет задание на ознакомление,
** `_Дата/время_`, дата "Ознакомиться до".
* При нажатии на кнопку *Отправить на ознакомление* происходит проверка параметров, и с помощью объекта `requestManager` отправляется запрос на сервер.

== Сборка и установка

. Откройте `/Samples.sln`.
. Соберите проект `Controls > AcquaintancePanel > AcquaintancePanelDesignerExtension`.
. Соберите проект `Controls > AcquaintancePanel > AcquaintancePanelServerExtension`.
. Откройте консоль в папке `Controls > AcquaintancePanel > AcquaintancePanelWebExtension` и выполните команду `npm install` и `npm run build:prod`.
. Скопируйте каталог `SamplesOutput\Plugins\AcquaintancePanelDesignerExtension` в каталог `Путь к директории с исполняемым файлом конструктора Web-разметок\Plugins`.
. Скопируйте каталог `SamplesOutput\Extensions\AcquaintancePanelServerExtension` в каталог `Путь к сайту {wc}а\Extensions`.
. Скопируйте файл `SamplesOutput\Extensions\ru\AcquaintancePanelServerExtension.resources.dll` в каталог `Путь к сайту {wc}а\Extensions\ru`.
. Скопируйте файл `SamplesOutput\Extensions\uk\AcquaintancePanelServerExtension.resources.dll` в каталог `Путь к сайту {wc}а\Extensions\uk`.
. Скопируйте каталог `SamplesOutput\Content\Modules\AcquaintancePanel` в каталог `Путь к сайту {wc}а\Content\Modules`.
. Перезапустите *{wcs-new}*.

== Проверка примера

. Запустите конструктор разметок.
. Скопируйте любую разметку просмотра.
. Выберите условия использования этой разметки.
. Откройте разметку и добавьте в неё новый элемент управления `_Пример боковой панели_`.
. Задайте желаемые параметры элемента управления. Для корректной работы задайте `editOperation = "Send for acquaintance"` или "Отправка на ознакомление".
. Сохраните разметку.
. Перезапустите *{wcs-new}*.
. Откройте карточку с этой разметкой.
. Убедитесь, что появился новый элемент управления, кнопку, при нажатии на которую появляется боковая панель.
. Заполните необходимые поля и нажмите *Отправить на ознакомление*.
. Должен запуститься бизнес-процесс, и указанным сотрудникам придет задание на ознакомление со ссылкой на документ.
