= Создание карточки пользовательского типа

Данный раздел содержит описание примера добавления в диалог создания карточки пользовательского типа.

Пример рассчитан на версию {wc}а {page-version} или выше.

include::ROOT:partial$excerpts.adoc[tags=wc-node]
include::ROOT:partial$excerpts.adoc[tags=vscode]

== Сборка и установка

. Открыть `/Samples.sln`
. Собрать проект `ServerExtensions > CreateCardDialog > CreateCardDialogServerExtension`
. Открыть консоль в папке `ServerExtensions > CreateCardDialog > CreateCardDialogWebExtension` и выполнить команду `npm install`, затем `npm update` и в конце `npm run build:prod`
. Скопировать каталог `SamplesOutput\Site\Extensions\CreateCardDialogServerExtension` в каталог `Путь к сайту {wc}а\Extensions`
. Скопировать файл `SamplesOutput\Site\Extensions\ru\CreateCardDialogServerExtension.resources.dll` в каталог `Путь к сайту {wc}а\Extensions\ru`
. Скопировать каталог `SamplesOutput\Site\Content\Modules\CreateCardDialogWebExtension` в каталог `Путь к сайту {wc}а\Content\Modules`
. Перезапустите *{wcs-new}*

== Проверка примера

. Запустить конструктор разметок.
. Выбрать библиотеку `ApprovalDesigner карточки`.
. Выбрать тип _Этап согласования_.
. Создать разметку создания и просмотра (Например, добавить элемент управления `_Строка_` и привязать его к свойству `MainInfo\Name`).
. Выбрать условия использования этих разметок.
. [[config]]В конфигурационном файле {wc}а `appsettings.json` в секции `Docsvision > Platform > CardTypes` добавить строку:
+
[source,json]
----
	{

        "CardTypeId": "0DB13C90-21B6-49D8-9070-8144DF97552A", <.>
        "CssClass": "approval-stage"
    }
----
<.> `0DB13C90-21B6-49D8-9070-8144DF97552A` -- идентификатор типа карточки этапа согласования.
+
. Разрешить создание карточек вида _Этап согласования_ в справочнике видов карточек.
. Перезапустите *{wcs-new}*.
. Открыть {wc} и нажать на кнопку *Создать*.
. Должен появиться новый тип карточки _Этап_, доступный для создания (фон -- фиолетовый).
. При выборе его, открывается созданная разметка, при этом фон боковой панели и шапки становится фиолетовым.

== Проект "CreateCardDialogServerExtension"

Проект реализует серверное расширение, в котором регистрируется фабрика для создания типа карточки _Этап_, отличная от стандартной.

== Проект "CreateCardDialogWebExtension"

Содержит клиентские скрипты реализующие веб-расширение, которое регистрирует тип карточки для его корректного отображения в {wc}е.

== Примечания

В базовом варианте, чтобы подключить к {wc}у карточку нового типа, достаточно внести изменения в конфигурационный файл {wc}а, <<config,как описано>> в инструкции проверки примера, а так же описать стиль класса `approval-stage-color`, например как:

[source,css]
----
.approval-stage-color {
  background-color: black;
}
----

Этот стиль применяется к элементам добавляемого типа карточки в диалоге создания карточки.

Если необходимо изменять цвет основных элементов управления {wc}а, например, основной кнопки, шапки, боковых панелей, следует реализовать стили по примеру, описанному в `approval-stage.scss`.

Локализованные наименования всех зарегистрированных типов карточек доступны на клиенте и содержатся в объекте `resources`. Наименование пользовательского типа доступно по ключу `CardType_\{CardTypeName}_DisplayName`, где `\{CardTypeName}` - наименование типа карточки в файле метаданных.

В собственном решении или элементе управления можно использовать цвета, связанные с каким-то типом карточки. Для этого следует воспользоваться системными CSS классами:

* `card-type-background-color` -- стандартный фон элемента типа карточки.
* `card-type-background-color-hover` -- стандартный фон элемента типа карточки при наведении мыши.
* `card-type-background-color-light` -- светлый фон элемента типа карточки.
* `card-type-background-color-light-hover` -- светлый фон элемента типа карточки при наведении мыши.
* `card-type-background-color-disabled` -- заблокированный фон элемента типа карточки, например, когда кнопка недоступна для нажатия.
* `card-type-foreground-color` -- стандартный цвет шрифта типа карточки.

Список может быть расширен, при необходимости обратитесь к документации разработчика.

Если определенная бизнес-логика реализована или необходимо её реализовать, например если требуется задать значение какого-то поля по умолчанию при создании карточки, можно подключить серверное расширение (см. `LayoutWebClientExtension.cs`) и реализовать в нем интерфейс `ICardFactory`, в котором реализуется собственная логика по созданию карточки или созданию карточки по шаблону.

.Фрагмент файла "LayoutWebClientExtension.cs"
[source,csharp]
----
namespace CreateCardDialogServerExtension
{

    public class LayoutWebClientExtension : WebClientExtension <.>
    {

        public LayoutWebClientExtension(IServiceProvider serviceProvider) <.>
            : base()
        {
        }

        public override string ExtensionName <.>
        {
            get { return Assembly.GetAssembly(typeof(LayoutWebClientExtension)).GetName().Name; }
        }

        public override Version ExtensionVersion <.>
        {
            get { return new Version(FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location).FileVersion); }
        }


        #region WebClientExtension Overrides

        public override void InitializeServiceCollection(IServiceCollection services) <.>
        {
            services.AddTransient<ICardLifeCycleEx, ApprovalStageCardLifeCycle>();
        }

        protected override List<ResourceManager> GetLayoutExtensionResourceManagers() <.>
        {
            return new List<ResourceManager>
            {
                { Resources.ResourceManager }
            };
        }

        #endregion
    }
}
----
<.> Задаёт описание расширения для {wc}а, которое задано в текущей сборке.
<.> Создаёт новый экземпляр `LayoutWebClientExtension`.
+
.Параметры:
* `serviceProvider` -- сервис-провайдер.
+
<.> Получить название расширения.
<.> Получить версию расширения.
<.> Регистрация типов в IoC-контейнере.
+
.Параметры:
* `containerBuilder` -- сборщик контейнеров.
+
<.> Получает менеджеры ресурсов для расширения разметки.
