= Реализация методов для работы со строками секций из разметок

Программисту предоставляется возможность добавить новую функциональность в механизмы создания и работы со строками секциями из разметок. Данная возможность реализуется с помощью специального класса с интерфейсом `IRowLifeCycleEx`. Интерфейс `IRowLifeCycleEx` предоставляет методы, которые вызываются на различных этапах работы со строкой секции:

[source,csharp]
----
public interface IRowLifeCycleEx
{
    Guid SectionId { get; } <.>
    Guid Create(SessionContext sessionContext, RowCreateLifeCycleOptions options); <.>
    bool Validate(SessionContext sessionContext, RowValidateLifeCycleOptions options, out List<ValidationResult> validationResults); <.>
    void OnSave(SessionContext sessionContext, RowSaveLifeCycleOptions options); <.>
    bool CanDelete(SessionContext sessionContext, RowDeleteLifeCycleOptions options, out string message); <.>
    void OnDelete(SessionContext sessionContext, RowDeleteLifeCycleOptions options); <.>
}
----
<.> Идентификатор секции, для строк которой предоставляется реализация интерфейса IRowLifeCycleEx.
<.> `Create` -- Вызывается при получении разметки создания новой строки секции.
<.> `Validate` -- Вызывается перед сохранением изменений строки в БД, с возможностью прервать сохранение.
<.> `OnSave` -- Вызывается при сохранении изменений строки -- позволяет добавить дополнительную логику в сохранение строки, но без возможности прервать сохранение.
<.> `CanDelete` -- Вызывается перед удалением строки секции -- позволяет прервать удаление.
<.> `OnDelete` -- Вызывается при удалении строки секции -- позволяет добавить дополнительную логику в удаление строки, но без возможности прервать удаление.

Указанные методы используются *исключительно* при выполнении стандартных операций со строками из разметок или с использованием JS WebAPI разметок. В других случаях методы интерфейса `IRowLifeCycleEx` не вызываются и не влияют на работу сервера {wc}а со строками секций.

Следующий код демонстрирует пример реализации класса, в котором определена собственная функция проверки данных строки секции перед сохранением изменений (`Validate`).

[source,csharp]
----
using System.Collections.Generic;
using DocsVision.BackOffice.CardLib.CardDefs;
using DocsVision.Platform.WebClient;
using DocsVision.WebClientLibrary.ObjectModel.Services.EntityLifeCycle;
using DocsVision.WebClientLibrary.ObjectModel.Services.EntityLifeCycle.Options;

public class RefPartnersCompaniesRowLifeCycle : DefaultRowLifeCycleEx <.>
{
    public RefPartnersCompaniesRowLifeCycle()
        : base(RefPartners.Companies.ID)
    {
    }

    public override bool Validate(SessionContext sessionContext, RowValidateLifeCycleOptions options, out List<ValidationResult> validationResults)
    {
        var isValid = base.Validate(sessionContext, options, out validationResults);
        var rowData = sessionContext.AdvancedCardManager.GetRowData(options.CardId, RefPartners.Companies.ID, options.RowId);
        var companyName = rowData.GetString(RefPartners.Companies.Name);
        if (string.IsNullOrEmpty(companyName))
        {
            isValid = false;
            var validationResult = new ValidationResult
            {
                Message = "Наименование компании не заполнено"
            };
            validationResults.Add(validationResult);
        }
        return isValid;
    }
}
----
<.> `RefPartnersCompaniesRowLifeCycle` наследуется от стандартной реализации интерфейса `IRowLifeCycleEx` -- класса `DefaultRowLifeCycle`, в котором уже реализованы необходимые методы. Помимо класса `DefaultRowLifeCycle` с реализацией по умолчанию API включает реализующий интерфейс `IRowLifeCycleEx` базовый класс `BaseRowLifeCycle` с абстрактными методами.

Метод `Validate` проверяет строку `rowId` на заполненность поля `RefPartners.Companies.Name`, и, если данное поле пустое, возвращает ошибку `validationResult`.

Полученный тип с интерфейсом `IRowLifeCycleEx` нужно добавить в IoC-контейнер в ядре расширения:

[source,csharp]
----
public override void InitializeServiceCollection(IServiceCollection services)
{
    services.AddTransient<IRowLifeCycleEx, RefPartnersCompaniesRowLifeCycle>();
}
----

Серверное расширение должно быть опубликовано стандартным образом.