= API для переопределения отрисовки таблицы

API параметр `tableRenderer` предназначен для переопределения отрисовки ЭУ `_Таблица исполнения_`. Параметр является объектом, в нём можно переопределить поля, каждое из которых позволяет переопределить отрисовку части таблицы.

Переопределить можно заголовок таблицы, ячейки, строки, столбцы, текст в ячейках, при этом не изменяя стандартную отрисовку.

Например, API позволяет в поле _Плановая дата завершения_ показывать не только дату, но и время.

[source,typescript]
----
export interface ITasksTableRenderer {
    renderTableBody?: (props: ITasksTableBodyProps) => JSX.Element; <.>
    renderHeader?: (props: ITasksTableHeaderRowProps) => JSX.Element; <.>
    renderHeaderCell?: (props: ITasksTableHeaderCellProps) => JSX.Element; <.>
    renderRow?: (props: ITasksTableRowProps) => JSX.Element; <.>
    renderCell?: (props: ITasksTableCellProps) => JSX.Element; <.>
    customAttributes?: (props: ITasksTableRowProps) => { [name: number]: unknown }; <.>
}
----
<.> Переопределение тела таблицы. Чтобы вернуть стандартную отрисовку, укажите `null`.
<.> Переопределение заголовка таблицы. Чтобы вернуть стандартную отрисовку, укажите `null`.
<.> Переопределение ячейки заголовка таблицы. Чтобы вернуть стандартную отрисовку, укажите `null`.
<.> Переопределение строки таблицы. Чтобы вернуть стандартную отрисовку, укажите `null`.
<.> Переопределение ячейки таблицы. Чтобы вернуть стандартную отрисовку, укажите `null`.
<.> Переопределение аттрибутов (значений) строки.
