:link: https://github.com/Docsvision/WebClient-Samples/tree/master/ServerExtensions/TableControl
:name: TableControl

= Отображение данных из связанных карточек

Данный раздел содержит описание примера серверного расширения. Пример содержит серверное расширение для отображения данных из связанных карточек в табличном контроле.
В разметку карточки _Документ УД/Исходящий_ добавляется таблица контрагентов, в колонках которой автоматически показываются e-mail и телефон выбранной в строке организации, загружаемые с сервера отдельным запросом.

include::../client/authorization.adoc[tags=link]

include::ROOT:partial$excerpts.adoc[tags=wc-node]
include::ROOT:partial$excerpts.adoc[tags=vscode]

== Сборка и установка

. Откройте `/Samples.sln`.
. Соберите проект `ServerExtensions > TableControl > TableControlServerExtension`.
. Откройте консоль в папке `ServerExtensions > TableControl > TableControlWebExtension` и выполнить команду `npm install`, затем `npm update` и в конце `npm run build:prod`.
. Скопируйте каталог `SamplesOutput\Content\Modules\TableControlWebExtension` в каталог `Путь к сайту Web-клиента\Content\Modules`.
. Скопируйте каталог `SamplesOutput\Extensions\TableControlServerExtension` в каталог `Путь к сайту Web-клиента\Extensions`.
. Перезапустите *{wcs-new}*.

== Проверка примера

. Запустите конструктор разметок.
. Скопируйте разметку просмотра исходящего документа.
. Выберите условия использования этой разметки.
. Откройте разметку и добавить в нее элемент управления `_Таблица_` в режиме _Редактирование по месту_ и 3 столбца. Для таблицы в поле _Источник данных_ секцию `Partners Receivers`.
. В первый столбец поместите элемент управления `_Подразделение котрагента_` в режиме _Редактирование по месту_, задайте имя `samplePartnersDepartment`. Значение _Поле данных_ выберите `Partner company`.
. Во второй столбец поместить элемент управления `_Метка_`, задайте имя `sampleDepartmentEmail`.
. В третий столбец поместить элемент управления `_Метка_`, задайте имя `sampleDepartmentPhone`.
. На событие `После открытия карточки` элемента `root` задайте функцию `sampleDocumentViewCardOpened`.
. Сохранить разметку.
. Перезапустите *{wcs-new}*.
. Откройте карточку с этой разметкой, добавить строку в таблицу, выбрать контрагента, обновить страницу.
. Убедиться, что почта и телефон контрагента заполнились.

== Проект "TableControlServerExtension"

Проект-расширение для {wc}а. Содержит бизнес-логику и скрипт для отображения данных из связанных карточек в табличном контроле.
Демонстрирует расширение функционала с помощью добавления новых сервисов, контроллеров.
Реализован контроллер `SamplePartnersController` с методом `GetPartnersInfo`, который вызывает сервис `ISamplePartnersService`, для получения информации о контрагентах:  `Phone`, `Email`, `Name`.

== Проект "TableControlWebExtension"

Содержит клиентский скрипт с функцией `sampleDocumentViewCardOpened`, которая вызывается на событие `После открытия карточки`. Функция отправляет запрос на сервер `getPartnersInfo` и заполняет таблицу вернувшимися данными.
