:link: https://github.com/Docsvision/WebClient-Samples/tree/master/ProjectTemplates/TemplateServerExtension
:name: TemplateServerExtension

= Создание и публикация серверного расширения

Серверное расширение представляет собой библиотеку DLL, разработанную на платформе .NET.

include::../client/authorization.adoc[tags=link]

== Перечень необходимых инструментов

include::ROOT:partial$excerpts.adoc[tags=wc-version]
include::ROOT:partial$excerpts.adoc[tags=vscode]
* {dv} WebClient SDK (запрашивается через портал ТП).

== Описание файлов проекта

* В корне репозитория расположено решение для Visual Studio (`Samples.sln`) и ключ для подписания сборок примеров (`StrongNameKey.snk`). Рекомендуется использовать Visual Studio {vscode-v}.
* `Assemblies` -- сборки, необходимые для использования примеров
* `ServerExtension.cs` -- входная точка расширение, в которой регистрируются сервисы и прочие сущности.
* `Sign.snk` -- файл подписи сборки. Для установки сборки должны быть подписаны. Рекомендуется сгенерировать новый файл подписи в настройках проекта.
* `Resource.resx`, `Resource.ru.resx` -- локализации, используемые в расширении.
* `Feature1` -- папка, содержащая реализацию некоторой функциональности.
* `Feature1/Feature1Controller.cs` -- класс, регистрирующий конечные точки Web API.
* `Feature1/IFeature1Service.cs` и `Feature1/Feature1Service.cs` -- интерфейс и реализация сервиса, реализующего логику обработки запроса.
* `Feature1/Models` -- классы моделей, используемых в сервисе и контроллере.

== Сборка и установка

.Чтобы создать серверное расширение:
. Убедитесь, что установлен {dv} WebClient SDK.
+
В этом случае в переменной окружения `DocsvisionWebClientSDK` содержится путь к его папке, например, `C:\Program Files (x86)\Docsvision\WebClient\SDK`.
+
. Установите шаблон серверного расширения и создайте на его основе новый проект с названием `LearnDocvisionServerExtension`.
+
. Обновите в проекте ссылки на зависимости.
+
****
include::ROOT:partial$excerpts.adoc[tags=versions]
****
+
. Реализуйте в проекте функции серверного расширения.
+
****
Примеры кода серверных расширений приведены в следующих пунктах раздела, а также в xref:web-client-samples.adoc[репозитории "ДоксВижн"].
****
+
. Настройте ядро серверного расширения.
+
****
Ядром серверного расширения называется файл `ServerExtension.cs` в проекте расширения. Ядро является производным от `WebClientExtension` классом, содержащим ссылки на реализуемые функции расширения.

[source,csharp]
----
public class ServerExtension : WebClientExtension
{
    public ServerExtension(IServiceProvider serviceProvider)
        : base()
    {
    }

    public override string ExtensionName <.>
    {
        get { return Assembly.GetAssembly(typeof(ServerExtension)).GetName().Name; }
    }

    public override Version ExtensionVersion <.>
    {
        get { return new Version(FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location).FileVersion); }
    }

    public override void InitializeServiceCollection(IServiceCollection services) <.>
    { 
<.>
        services.AddSingleton<IFeature1Service, Feature1Service>();
    }

    protected override List<ResourceManager> GetLayoutExtensionResourceManagers()
    {
        return new List<ResourceManager>
        {

        };
    }
<.>

}
----
<.> Название расширения.
<.> Версия расширения.
<.> Метод регистрации добавляемых расширением сервисов, преобразователей, конвертеров и т.п. в IoC контейнере.
<.> Примеры регистрации.
<.> Далее идут функции, возвращающие реализованные функции серверного расширения.

Описание изменений, которые необходимо выполнить в ядре расширения, приведено в описании примеров расширений, добавляющих обработчики событий и локализованные ресурсы.

В серверном расширении {wc}а используется IoC контейнер, реализованный с использованием библиотеки Autofac. Описание данной библиотеки и её возможностей см. на сайте https://autofac.org/[autofac.org].
****
+
. Скомпилируйте проект.
+
****
В результате будет получен файл DLL с ядром серверного расширения и реализуемыми функциями, а также файлы DLL с локализованными ресурсами.
****
+
. Скопируйте `safeprojectnamesafeprojectname.dll` и `safeprojectnamesafeprojectname.dll.pdb` из папки menu:bin[WebClient > Bin] в menu:Каталог-установки-{wc}а[Site > bin].
+
[WARNING]
====
Расширения можно устанавливать в папки menu:Site[Extensions] и menu:Site[bin]. В ходе разработки расширения можно удобнее устанавливать в папку menu:Site[bin], т.к. это избавляет от необходимости перезапускать *{wcs-new}* при установке сборок.

В ресурсной поставке рекомендуется устанавливать сборки в папку menu:Site[Extensions], чтобы проще было видеть, какие расширения установлены в {wc}е. Однако этот способ требует перезапуска *{wcs-new}* при установке или обновлении сборки.
====
+
. Перезапустите *{wcs-new}*.

== Проверка работы

. Откройте {wc}.
. Откройте диалог "О программе" и убедитесь, что расширение присутствует в списке подключенных расширений.
. Откройте произвольный документ и в консоли браузера выполните:
+
 $ await layoutManager.cardLayout.getService("requestManager").post("api/Feature1/Action1", JSON.stringify({ documentId: layoutManager.cardLayout.getService("cardId") }));
+
. Обновите документ, убедиться, что в названии добавился знак.
