= Работа с сервисом жизненного цикла объектов {wc}а

Рассмотренные в пунктах xref:server/card-factory.adoc[] и xref:server/row-factory.adoc[] компоненты, которые позволяют внести изменения в механизмы создания, изменения и удаления карточек и строк секций из разметок, доступны программисту через специальный сервис `ILifeCycleServiceEx`. Данный сервис определяет методы:

* `GetCardLifeCycle` -- Возвращает реализацию интерфейса `ICardLifeCycleEx` для указанного типа карточек.
* `GetRowLifeCycle` -- Возвращает реализацию интерфейса `IRowLifeCycleEx` для указанной секции.

Следующий код демонстрирует способ получения сервиса `ICardLifeCycleEx` и его использования в веб-методе для создания карточки по шаблону:

// no-code-check
[source,csharp]
----
public class CardServiceController : ApiController
{
    private readonly ILifeCycleServiceEx lifeCycleService;
    private readonly ICurrentObjectContextProvider currentObjectContextProvider;

    public CardServiceController(ILifeCycleServiceEx lifeCycleService, ICurrentObjectContextProvider currentObjectContextProvider) <.>
    {
        this.lifeCycleService = lifeCycleService;
        this.currentObjectContextProvider = currentObjectContextProvider;
    }

    [HttpGet]
    public Guid CreateByTemplate(Guid templateId)
    {
        var sessionContext = currentObjectContextProvider.GetOrCreateCurrentSessionContext();
        var documentCardLifeCycle = lifeCycleService.GetCardLifeCycle(CardDocument.ID); <.>
        var newDocumentId = Guid.Empty;
        if (templateId != Guid.Empty)
        {
            newDocumentId = documentCardLifeCycle.Create(sessionContext, new CardCreateLifeCycleOptions()
            {
                TemplateId = templateId <.>
            });
        }
        return newDocumentId;
    }
}
----
<.> Принимаем требуемый сервис в конструкторе.
<.> Получаем интерфейс для работы с карточкой типа `CardDocument`.
<.> Используем метод создания карточки по шаблону.
