= Работа с сервисом жизненного цикла объектов {wc}а

Рассмотренные в пунктах xref:server/card-factory.adoc[] и xref:server/row-factory.adoc[] компоненты, которые позволяют внести изменения в механизмы создания, изменения и удаления карточек и строк секций из разметок, доступны программисту через специальный сервис `ILifeCycleServiceEx`. Данный сервис определяет методы:

* `GetCardLifeCycle` -- Возвращает реализацию интерфейса `ICardLifeCycleEx` для указанного типа карточек.
* `GetRowLifeCycle` -- Возвращает реализацию интерфейса `IRowLifeCycleEx` для указанной секции.

Следующий код демонстрирует способ получения сервиса `ICardLifeCycleEx` и его использования в веб-методе для создания карточки по шаблону:

// no-code-check
[source,csharp]
----
public class CardServiceController : ApiController
{
    private readonly ILifeCycleServiceEx lifeCycleService;
    
    public CardServiceController(ILifeCycleServiceEx lifeCycleService) <.>
    {
        this.lifeCycleService = lifeCycleService;
    }

    [HttpGet]
    public Guid CreateByTemplate(Guid cardTypeId)
    {
        var documentCardLifeCycle = lifeCycleService.GetCardLifeCycle(CardDocument.ID); <.>
        if (templateId != Guid.Empty)
        {
            var newDocumentId = documentCardLifeCycle.CreateFromTemplate(sessionContext, templateId, null); <.>
        }
        return newDocumentId;
    }
}
----
<.> Принимаем требуемый сервис в конструкторе.
<.> Получаем интерфейс для работы с карточкой типа CardDocument.
<.> Используем метод создания карточки по шаблону.
