:link: https://github.com/Docsvision/WebClient-Samples/tree/master/ClientScripts/AdvancedTypeScript/AdaptiveMenuBar
:name: AdaptiveMenuBar

= Всплывающее меню

Данный раздел содержит описание примера работы с всплывающим меню. Проект-расширение клиентской части {wc}а. Содержит клиентский скрипт c функцией `showAdaptiveMenuBar`, реализующей отображение `AdaptiveMenuBarComponent`.

include::authorization.adoc[tags=link]

`AdaptiveMenuBarComponent` -- React компонент, представляющий всплывающее меню.

include::ROOT:partial$excerpts.adoc[tags=wc-node]

== Сборка и установка

. Откройте консоль в папке `AdaptiveMenuBarWebExtension` и выполните команду npm `install`, затем `npm update` и в конце `npm run build:prod`.
. Скопируйте каталог `SamplesOutput\Content\Modules\AdaptiveMenuBarWebExtension` в каталог `Путь к сайту {wc}а\Content\Modules`.
. Перезапустите *{wcs-new}*.

== Проверка примера

. Запустите конструктор разметок.
. Импортируйте разметку из файла `AdaptiveMenuBarLayout.xml` без условий использования. При этом будет добавлена разметка в тип карточки документ, вид _ДокументУД\Исходящий_.
. Сделайте решение `AdaptiveMenuBarLayout` активным.
. Перезапустите *{wcs-new}*.
. Откройте новый документ _ДокументУД\Исходящий_ и нажмите кнопку *Редактировать*. При этом должна открыться разметка с кнопкой вызова модального окна и текстовым полем.
. При нажатии на кнопку `ShowAdaptiveMenuBar` появляется всплывающее меню. При нажатии на пунктах меню их название появляется во всплывающем сообщении.
