:link: https://github.com/Docsvision/WebClient-Samples/tree/master/ClientScripts/TypeScript/ChangeStateByScript
:name: ChangeStateByScript

= Обработка события изменения состояния карточки

При изменении состояния карточки из пользовательского интерфейса {wc}а вызывается событие `*Перед изменением состояния карточки*` разметки карточки (корневой элемент разметки), которое может быть обработано в клиентском скрипте.

include::authorization.adoc[tags=link]

Данное событие является прерываемым -- может быть использовано для отмены изменения состояния карточки.

Ниже приведён код обработчика события изменения состояния карточки (Документ, Задание):

[source,typescript]
----
async function changeState(sender: Layout, e: CancelableEventArgs<ICardStateChangingEventArgs>) {
    e.wait();

    if (await myCheckPossibility()){ <.>
        e.accept(); <.>
    } else {
        sender.getService($MessageWindow).showWarning("Операция " + e.data.operationId  + " запрещена"); <.>
        e.cancel(); <.>
    }
}
----
<.> Функция `myCheckPossibility` -- пользовательский код, содержащий собственную логику.
<.> Подтверждаем выполнение операции. Обязательно, если вызвали `e.wait`.
<.> Показываем сообщение о запрете операции с указанием идентификатора операции.
<.> Для отмены операции, при необходимости, вызываем `e.cancel`.

Для карточки _Задание_ после изменения состояния карточки будет вызвано событие `*После изменения состояния карточки*` элемента управления `_Кнопки операций задания_`.
