= Проверка данных

Данный раздел содержит описание примера проверки действительности данных.
Выполнить проверку, что заполнено определенное текстовое поле и количество символов не превышает 100.

Проект-расширение клиентской части {wc}а. Содержит клиентский скрипт с функцией `validateTextBoxControl`, реализующей валидацию данных ЭУ.

include::ROOT:partial$excerpts.adoc[tags=wc-node]

== Сборка и установка

. Откройте консоль в папке `ControlValidationWebExtension` и выполните команду `npm install`, затем `npm update` и в конце `npm run build:prod`.
. Скопируйте каталог `SamplesOutput\Content\Modules\ControlValidationWebExtension` в каталог `Путь к сайту {wc}а\Content\Modules`.
. Перезапустите *{wcs-new}*

== Проверка примера

. Запустите конструктор разметок.
. Импортируйте решение из файла `ControlValidationLayout.xml`.
. Сделайте решение _ControlValidationLayout_ активным для карточки типа Документ вида _ДокументУД/Исходящий_.
. На разметке расположен ЭУ `_Текст_` и кнопки сохранения/отмены.
. Перезапустите *{wcs-new}*
. Откройте документ ДокументУД\Исходящий и нажать кнопку редактировать. При этом должна открыться разметка с ЭУ `_Текст_` и кнопками сохранения.
. Если в ЭУ `_Текст_` нет текста или длина текста превышает 100 символов, то при нажатии кнопки *Сохранить* возникает сообщение об ошибке и изменения не сохраняются.

NOTE: Данный пример демонстрирует только доступ к элементу разметки.
При реализации расширений рекомендуется использовать экспорт разметок в виде Решения.
