:link: https://github.com/Docsvision/WebClient-Samples/tree/master/ClientScripts/TypeScript/ControlsRelation
:name: ControlsRelation

= Взаимодействие элементов управления

Данный раздел содержит описание примера взаимодействия элементов управления. При установке `_Флажка_` отображается другой скрытый ЭУ. Проект-расширение клиентской части {wc}а. Содержит клиентский скрипт с функцией `showRelatedControl` реализующей взаимодействие ЭУ.

include::authorization.adoc[tags=link]


include::ROOT:partial$excerpts.adoc[tags=wc-node]

== Сборка и установка

. Откройте консоль в папке ControlsRelationWebExtension и выполните команду `npm install`, затем `npm update` и в конце `npm run build:prod`
. Скопируйте каталог SamplesOutput\Content\Modules\ControlsRelationWebExtension в каталог "Путь к сайту {wc}а\Content\Modules"
. Перезапустите *{wcs-new}*

== Проверка примера

. Запустите конструктор разметок.
. Импортируйте решение из файла `ControlsRelationLayout.xml`.
+
.Либо создайте собственное решение:
.. Создайте для расширения разметку.
.. Добавьте в разметку `_Блок_`, в него `_Флажок_` и `_Метка_`.
.. Для `_Метки_` снимите флаг со свойства `*Видимость*` и запишите отображаемое имя в свойство `*Текст метки*`.
.. Для `_Флажка_` добавьте на `*После смены данных*` вызов функции `showRelatedControl:ControlsRelationExt`, где `showRelatedControl` -- имя функции, а `ControlsRelationExt` -- псевдоним расширения, настроенный в `ImportControlsRelationWebExtension.js`.
+
. Сделайте решение `ControlsRelationLayout` или собственное активным для карточки типа _Документ_ вида _ДокументУД/Исходящий_.
. На разметке расположен `_Флажок_` и `_Метка_`, причем `_Метка_` скрыт.
. Перезапустите *{wcs-new}*.
. Откройте документ _ДокументУД\Исходящий_ и нажать кнопку *Редактировать*. При этом должна открыться разметка с ЭУ `_Флажок_`.
. При нажатии на `_Флажок_`, элемент управления `_Метка_` должен появиться.

NOTE: Данный пример демонстрирует только доступ к элементу разметки.
При реализации расширений рекомендуется использовать экспорт разметок в виде Решения.
