:link: https://github.com/Docsvision/WebClient-Samples/tree/master/ClientScripts/TypeScript/CopyValueToControl
:name: CopyValueToControl

= Копирование значения ЭУ

Данный раздел содержит описание примера взаимодействия ЭУ: копирование значения. При завершении ввода значения в один ЭУ, это же значение копируется в другой. Проект-расширение клиентской части {wc}а. Содержит клиентский скрипт c функцией `copyValueToControl`, реализующей копирование данных одного ЭУ в другой.

include::authorization.adoc[tags=link]

include::ROOT:partial$excerpts.adoc[tags=wc-node]

== Сборка и установка

. Откройте консоль в папке CopyValueToControlWebExtension и выполните команду `npm install`, затем `npm update` и в конце `npm run build:prod`
. Скопируйте каталог SamplesOutput\Content\Modules\CopyValueToControlWebExtension в каталог "Путь к сайту {wc}а\Content\Modules"
. Перезапустите *{wcs-new}*

== Проверка примера

. Запустите конструктор разметок.
. Импортируйте решение из файла `CopyValueToControlLayout.xml`.
+
.Либо создайте собственное решение:
.. Создайте для расширения разметку.
.. Добавьте в разметку `_Блок_`, в него два ЭУ `_Текст_`.
.. Задайте для первого ЭУ `_Текст_` режим редактирования по месту, на событие  `*После смены данных*` добавьте вызов функции `copyValueToControl:CopyValueToControlExt`.
+
. Сделайте решение `CopyValueToControlLayout` или собственное активным для карточки типа _Документ_ вида _ДокументУД/Исходящий_.
. На разметке расположено два ЭУ `_Текст_`.
. Перезапустите *{wcs-new}*.
. Откройте документ _ДокументУД\Исходящий_ и нажать кнопку *Редактировать*. При этом должна открыться разметка с двумя ЭУ `_Текст_`.
. Если в первый из них добавить текст, текст появится во втором.

NOTE: Данный пример демонстрирует только доступ к элементу разметки.
При реализации расширений рекомендуется использовать экспорт разметок в виде Решения.
