= Web-расширение для Модуля интеграции с операторами ЭДО

Данный раздел описывает пример изменения стандартных сценариев web-расширения {wc}а для Модуля интеграции с операторами ЭДО. Проект `SendOutgoingToUserDepartmentBoxEdiWebExtension` содержит клиентский скрипт, позволяющий изменить стандартный сценарий подписания и отправки исходящего документа.

Пример рассчитан на версию {wc}а {page-version}.

.Перечень необходимых инструментов:
* https://nodejs.org/en/[NodeJS v16.20.0+]

== Сборка и установка

. Откройте консоль в папке `SendOutgoingToUserDepartmentBoxEdiWebExtension` и выполните команду `npm install`, потом  `npm update` и в конце `npm run build:prod`.
. Скопируйте каталог `SamplesOutput\Site\Content\Modules\SendOutgoingToUserDepartmentBoxEdiWebExtension` в каталог `{wcd}\Content\Modules`.
. Перезапустите IIS.

== Проверка примера

. Запустите {kvr}.
. Импортируйте решение из файла `SendOutgoingToUserDepartmentBoxEdiWebExtension.xml`
. Сделайте решение `EdiSamples` активным для карточки типа Документ вида ДокументУД/Исходящий
. Убедитесь, что в разметке на событие `*При щелчке*` ЭУ кнопки отправки назначен обработчик `sendFromUserDepartmentBox`.
. Перезапустите IIS.
. Откройте _DVExplorer_. В карточке _Справочник настройки ЮЗДО_ последовательно перейдите в секцию menu:Операторы[Организации > Ящики организации] и добавьте ещё один ящик, скопировав существующий.
. Измените имя вновь добавленного ящика.
. Откройте исходящий документ нажатием кнопки *Подписать и отправить*.
. Убедитесь, что подписание и отправка происходят без открытия диалога выбора ящика для отправки и документ отправляется с почтового ящика подразделения подписывающего сотрудника.

С полным кодом примера web-расширения можно ознакомиться в https://github.com/Docsvision/WebClient-Samples/tree/master_net45/ClientScripts/TypeScript/EdiWebExtension(WebC17)[репозитории примеров {wc}а] на GitHub.
