:link: https://github.com/Docsvision/WebClient-Samples/tree/master/ClientScripts/TypeScript/FileListHighlightRow
:name: FileListHighlightRow

= Работа со строкой данных элемента управления "Список файлов" (fileList)

Пример взаимодействия со строками элемента управления `_Список файлов_` (`fileList`). Проект представляет собой xref:client/create-publish.adoc[клиентское расширение]. Расширение добавляет к строке элемента управления красную обводку при скачивании файла.

// include::page$client/grid-context.adoc[tags=start]

Основной код расширения содержит скрипт `fileListHighlightRow` в качестве обработчика события `*После загрузки версии файла*` элемента управления `fileList` в конструкторе разметок.

.EventHandler.ts
[source,typescript]
----
export async function fileListHighlightRow(sender: FileListControl, event: IFileVersionDownloadingArgs) {
    const fileItem = event.fileItem;
	const customClass = "file-list-row_red-border";

    if (!event.fileItem?.cssClasses?.includes(customClass)) {
        sender.toggleRowClass(fileItem, customClass);
    }
}
----

Данный скрипт представляет пример получения объекта `fileItem`, представляющего информацию о файле из аргументов события. Выполняется исследование его свойства, после чего вызывается метод `toggleRowClass` ЭУ `FileListControl` для переключения стилей файла.

.Index.ts
[source,typescript]
----
extensionManager.registerExtension({ <.>
    name: "FileListHighlightRow",
    version: "1.0",
    globalEventHandlers: [ EventHandler ]
})
----
<.> Регистрация расширения позволяет корректно установить все обработчики событий, сервисы и прочие сущности web-приложения.


== Проверка примера

. Откройте папку с элементом управления и добавленным обработчиком события.
. Скачайте версию файла.