:link: https://github.com/Docsvision/WebClient-Samples/tree/master/ClientScripts/TypeScript/GridColumnBackgroundRows
:name: GridColumnBackgroundRows

= Взаимодействие колонки таблицы со строками

Данный раздел содержит описание примера взаимодействия новой колонки таблицы с её строками. Проект-расширение клиентской части {wc}а. Содержит клиентский скрипт позволяющий добавить новую колонку в таблицу, отрисовать элемент в её ячейках, при нажатии на который открывается палитра. Изменяя палитру, будет изменяться фон строки, в которой находится ячейка.

include::authorization.adoc[tags=link]

include::ROOT:partial$excerpts.adoc[tags=wc-node]

== Сборка и установка

. Откройте консоль в папке `GridColumnBackgroundRowsWebExtension` и выполните команду `npm install`, затем `npm update` и в конце `npm run build:prod`.
. Скопируйте каталог `SamplesOutput\Content\Modules\GridColumnBackgroundRowsWebExtension` в каталог `Путь к сайту {wc}а\Content\Modules`.
. Перезапустите *{wcs-new}*.

== Проверка примера

. Откройте папку с таблицей, где в колонке _Фон строки_, нажмите на любое поле ввода и изменить цвет.

NOTE: Данный пример демонстрирует только взаимодействие новой колонки, её ячеек и фон строки, в которой они находятся, с помощью скрипта. Сохранение выбранного цвета строки не реализовано, поэтому при обновлении страницы цвет сбросится. При необходимости сохранение можно добавить в классе `BackgroundRowsService`.
