= Настройка страницы входа

Данный раздел содержит описание примера кастомизации страницы входа в {wc}.

В этом примере демонстрируется возможность внедрения своего кода на страницу входа в {dv} {wc}, а именно:

* Выполнение кода при определённых событиях(тип `LoginEvents` в модуле `@docsvision/webclient/Account`).
* Подмена текста на страницы(объект `defaultLoginResources` в модуле `@docsvision/webclient/Account`).
* Замена компонентов страницы(объект `LoginView` в модуле `@docsvision/webclient/Account/LoginContainer`).
* Добавление стилей на страницу.

include::ROOT:partial$excerpts.adoc[tags=wc-node]

== Сборка и установка

. Откройте консоль в папке `ClientScripts\TypeScript\LoginPage` и выполните команду `npm install`, затем `npm run build:prod`.
. Скопируйте каталог `SamplesOutput\Content\Account\Scripts` в каталог `Путь к сайту {wc}а\Content\Account\Scripts`.
. Перезапустите *{wcs-new}*.

== Дополнительная информация

* Рекомендуется осуществлять сборку в виде umd модуля.
* Для корректной работы расширения нужно создать файл или файлы с расширением `.js` и положить в папку `Путь к сайту {wc}а\Content\Account\Scripts`, код будет выполнен перед загрузкой приложения и выполнением `ReactDOM.render()`.
* Чтобы добавить стили, нужно создать файл или файлы с расширением `.сss` и положить в папку `Путь к сайту {wc}а\Content\Account\Styles`, стили загружаются после основных стилей страницы.
* Входной точкой для внедрения кода на страницу является объект `loginExtensionManager` доступный глобально через объект `windows`.
* Код расширения будет выполнен перед загрузкой приложения и выполнением `ReactDOM.render()`, но после загрузки библиотек React и ReactDOM.
* Методы `loginExtensionManager`, а также возможные ресурсы, компоненты и события для замены обозначены в виде типов и интерфейсов в модуле `@docsvision/webclient/Account`.
