= Блок сообщений

Данный раздел содержит описание примера последовательного вывода нескольких информационных сообщений. Проект-расширение клиентской части {wc}а. Содержит клиентский скрипт c функцией `showMessages` реализующей последовательный вывод `MessageBox`.

include::ROOT:partial$excerpts.adoc[tags=wc-node]

== Сборка и установка

. Откройте консоль в папке `MessageBoxWebExtension` и выполните команду `npm install`, затем  `npm update` и в конце `npm run build:prod`.
. Скопируйте каталог `SamplesOutput\Content\Modules\MessageBoxWebExtension` в каталог `Путь к сайту {wc}а\Content\Modules`.
. Перезапустите *{wcs-new}*.

== Проверка примера

. Запустите конструктор разметок
. Импортируйте разметку из файла `MessageBoxLayout.xml` без условий использования. При этом будет добавлена разметка в тип карточки документ, вид _ДокументУД\Исходящий_
. Задайте для разметки условия использования, поменяв также порядок разметок в условиях использования, чтобы разметка стала первой разметкой для редактирования
. Перезапустите *{wcs-new}*.
. Откройте новый документ _ДокументУД\Исходящий_ и нажмите кнопку *Редактировать*. При этом должна открыться разметка с кнопкой вызова сообщений.
. При нажатии на кнопку `ShowMessages` последовательно появляются диалоговые окна:  информационное сообщение с текстом `Это информационное сообщение`, предупреждающее сообщение с текстом `Это предупреждающее сообщение`, сообщение об ошибке с текстом `Это сообщение об ошибке`, диалог подтверждения с текстом `Выберите кнопку`. В случае нажатия той или иной кнопки выводится сообщение.
