:link: https://github.com/Docsvision/WebClient-Samples/tree/master/ClientScripts/AdvancedTypeScript/ModalDialog
:name: ModalDialog

= Модальное окно

Данный раздел содержит описание примера работы с модальным окном. Проект-расширение клиентской части {wc}а. Содержит клиентский скрипт c функцией `showModalDialog` реализующей отображение `ModalDialog`. `ModalDialogComponent` -- React компонент, отвечающий за представление модельного окна и его событий.

include::authorization.adoc[tags=link]

include::ROOT:partial$excerpts.adoc[tags=wc-node]

== Сборка и установка

. Откройте консоль в папке `ModalDialogWebExtension` и выполните команду `npm install`, затем `npm update` и в конце `npm run build:prod`.
. Скопируйте каталог `SamplesOutput\Content\Modules\ModalDialogWebExtension` в каталог `Путь к сайту {wc}а\Content\Modules`.
. Перезапустите *{wcs-new}*.

== Проверка примера

. Запустите конструктор разметок
. Импортируйте разметку из файла `ModalDialogLayout.xml` без условий использования. При этом будет добавлена разметка в тип карточки документ, вид _ДокументУД\Исходящий_
. Задайте для разметки условия использования, поменяв также порядок разметок в условиях использования, чтобы разметка стала первой разметкой для редактирования
. Перезапустите *{wcs-new}*.
. Откройте новый документ _ДокументУД\Исходящий_ и нажмите кнопку *Редактировать*. При этом должна открыться разметка с кнопкой вызова модального окна и текстовым полем.
. При нажатии на кнопку *ShowModalDialog* отображается модальное окно, в котором присутствует текстовое поле для ввода. После ввода сообщения и нажатия на кнопку *ОК*, значение из этого поля копируется в текстовое поле на разметке и сохраняется в качестве имени документа.
