:link: https://github.com/Docsvision/WebClient-Samples/tree/master/ClientScripts/AdvancedTypeScript/ModalSidebar
:name: ModalSidebar

= Боковая панель

Данный раздел содержит описание примера работы с боковой панелью. Проект-расширение клиентской части {wc}а. Содержит клиентский скрипт c функцией `showModalSidebar` реализующей отображение `ModalSidebar`. `ModalSidebarComponent` -- React компонент, отвечающий за представление боковой панели и её событий.

include::authorization.adoc[tags=link]

include::ROOT:partial$excerpts.adoc[tags=wc-node]

== Сборка и установка

. Откройте консоль в папке `ModalSidebarWebExtension` и выполните команду `npm install`, затем `npm update` и в конце `npm run build:prod`.
. Скопируйте каталог `SamplesOutput\Content\Modules\ModalSidebarWebExtension` в каталог `Путь к сайту {wc}а\Content\Modules`.
. Перезапустите *{wcs-new}*.

== Проверка примера

. Запустите конструктор разметок
. Импортируйте разметку из файла `ModalSidebarLayout.xml` без условий использования. При этом будет добавлена разметка в тип карточки документ, вид _ДокументУД\Исходящий_.
. Задайте для разметки условия использования, поменяв также порядок разметок в условиях использования, чтобы разметка стала первой разметкой для редактирования.
. Перезапустите *{wcs-new}*.
. Откройте новый документ _ДокументУД\Исходящий_ и нажмите кнопку *Редактировать*. При этом должна открыться разметка с кнопкой вызова боковой панели и текстовым полем.
. При нажатии на кнопку *ShowModalSidebar* отображается боковая панель, в котором присутствует текстовое поле для ввода. После ввода сообщения и нажатия на кнопку *ОК*, значение из этого поля копируется в элемент управления `_textBox1_` разметки.
