= Проверка данных ЭУ

Данный раздел содержит описание примера проверки, изменения и отмены изменения состояния карточки. Подписаться на событие изменения состояния, провести проверку какого-нибудь поля и случае, если проверка не прошла, выдать предупреждающее сообщение и состояние не менять.

Проект-расширение клиентской части {wc}. Содержит клиентский скрипт с функцией-обработчиком события `validateOnStateChanging`, проверку данных ЭУ
при смене состояния.

include::ROOT:partial$excerpts.adoc[tags=wc-node]

== Сборка и установка

. Откройте консоль в папке `ValidateOnStateChangingWebExtension` и выполните команду `npm install`, затем `npm update` и в конце `npm run build:prod`.
. Скопируйте каталог `SamplesOutput\Content\Modules\ValidateOnStateChangingWebExtension` в каталог `Путь к сайту {wc}а\Content\Modules`.
. Перезапустите *{wcs-new}*.

== Проверка примера

. Запустите конструктор разметок.
. Импортируйте решение из файла `ValidateOnStateChangingLayout.xml`.
. Сделайте решение `ValidateOnStateChangingLayout` активным для карточки типа Документ вида _ДокументУД/Исходящий_.
. На разметке расположен ЭУ `_Текст_` и кнопки операций (Start approving и др.) по изменению состояния карточки.
. Перезапустите *{wcs-new}*.
. Откройте новый документ _ДокументУД\Исходящий_ и нажать кнопку редактировать. При этом должна открыться разметка с ЭУ `_Текст_` и кнопками изменения состояния. Часть кнопок будет неактивна, это зависит от настроек ролевой модели.
. Если в ЭУ `_Текст_` нет текста или длина текста превышает 100 символов, то при нажатии на кнопку изменения состояния возникает сообщение об ошибке и состояние не изменяется.
. В случае, если ЭУ `_Текст_` проходит валидацию, то состояние карточки меняется. Например при выполнении операции `Start approving` с состояния `Drafting` на состояние `Is approving`.
. При этом  кнопки перехода исчезают, т.к. в состоянии `Is approving` операции `Start approving` и др. не доступны.

NOTE: Данный пример демонстрирует только доступ к элементу разметки.
При реализации расширений рекомендуется использовать экспорт разметок в виде Решения.
