= Разработка расширения с локализованными ресурсами

При необходимости использовать локализованные ресурсы в расширении можно их добавить при регистрации расширения в `Index.ts`.

Чтобы создать расширение, добавляющее новые локализованные ресурсы, выполните приведенную далее инструкцию.

. Создайте xref:client/with-event-handlers.adoc[проект клиентского расширения].
+
. Создайте в папке `src` файл TypeScript (`.ts`, `.tsx`) со следующим содержимым:
+
[source,typescript]
----
import { ILocalizationsMap } from "@docsvision/webclient/System/ILocalizationsMap"; <.>
   
export function getLocalizedResources(): ILocalizationsMap {
    let cultureMap: ILocalizationsMap = {};
    cultureMap["en"] = {
        "Resource_One": "Sample",
        "Resource_Two": "Sample 2"
    };
       cultureMap["ru"] = {
        "Resource_One": "Пример",
        "Resource_Two": "Пример 2"
    };
    return cultureMap;
}
----
<.> Импортируем необходимые сущности из модуля.
+
****
В данном коде выполняется добавление двух ресурсов `Resource_One` и `Resource_Two` для языков русский (`ru`) и английский (`en`).

Функция `getLocalizedResources` (можно использовать другое название) возвращает массив добавляемых локализованных ресурсов, в котором каждый элемент соответствует определённой локали. Например, следующий участок кода отвечает за добавление ресурсов для локали `ru` (русский):

[source,typescript]
----
cultureMap["ru"] = {
    "Resource_One": "Пример",
    "Resource_Two": "Пример 2"
};
----
****
+
. Измените содержимое файла `Index.ts`.
+
[source,typescript]
----
import { getLocalizedResources } from "./LocalizedResource"; <.>
import { extensionManager } from "@docsvision/webclient/System/ExtensionManager";
import { ILocalizationsMap } from "@docsvision/webclient/System/ILocalizationsMap";

extensionManager.registerExtension({ <.>
    name: "Client extension with localization",
    version: "1.0",
    getLocalizations(): ILocalizationsMap {
        return getLocalizedResources();
        }
})
----
<.> Добавьте строку импорта функции getLocalizedResources из добавленного в 2 файла (в примере -- LocalizedResource).
<.> Добавьте в registerExtension функцию getLocalizations, которая должна вызывать импортированную в 1 функцию.

== Пример использования ресурсов

[source,typescript]
----
export function onButtonClick(sender: LayoutControl, args: IEventArgs) {
     const messageWindow - sender.getService($MessageWindow);
     messageWindow.showInfo(resoures.Resource_One);
}
----
